package service

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/bruin-data/bruin/pkg/config"
	"github.com/bruin-data/bruin/pkg/jinja"
	"github.com/bruin-data/bruin/pkg/pipeline"
	"github.com/bruin-data/bruin/pkg/query"
	"github.com/bruin-data/bruin/pkg/scheduler"
	"go.uber.org/zap"
)

type assetCheckRenderOutcome struct {
	stages []AssetRenderStage
	issues []AssetRenderIssue
	status AssetRenderStatus
}

// renderCheckCaptureConnection receives the query generated by Bruin's actual
// check operator and returns the expected synthetic count. It never opens a
// warehouse connection or executes user SQL.
type renderCheckCaptureConnection struct {
	expected int64
	query    string
}

func (c *renderCheckCaptureConnection) Select(_ context.Context, q *query.Query) ([][]interface{}, error) {
	if q == nil {
		return nil, fmt.Errorf("check operator submitted an empty query")
	}
	c.query = q.Query
	return [][]interface{}{{c.expected}}, nil
}

type renderCheckCaptureManager struct {
	connection      *renderCheckCaptureConnection
	connectionTypes map[string]string
}

var _ config.ConnectionGetter = (*renderCheckCaptureManager)(nil)
var _ directCheckConnectionTypeGetter = (*renderCheckCaptureManager)(nil)

func (m *renderCheckCaptureManager) GetConnection(string) any {
	return m.connection
}

func (m *renderCheckCaptureManager) GetConnectionType(name string) string {
	for connectionName, connectionType := range m.connectionTypes {
		if strings.EqualFold(strings.TrimSpace(connectionName), strings.TrimSpace(name)) {
			return connectionType
		}
	}
	return ""
}

func renderCheckConnectionTypes(ctx context.Context) map[string]string {
	if environment, ok := ctx.Value(config.EnvironmentContextKey).(*config.Environment); ok && environment != nil && environment.Connections != nil {
		return environment.Connections.ConnectionsSummaryList()
	}
	return map[string]string{}
}

func renderAssetCheckStages(ctx context.Context, pl *pipeline.Pipeline, asset *pipeline.Asset, renderer *jinja.Renderer) assetCheckRenderOutcome {
	outcome := assetCheckRenderOutcome{
		stages: []AssetRenderStage{},
		issues: []AssetRenderIssue{},
		status: AssetRenderStatusOK,
	}
	if pl == nil || asset == nil || !assetHasRuntimeChecks(asset) {
		return outcome
	}

	capture := &renderCheckCaptureConnection{}
	manager := &renderCheckCaptureManager{
		connection:      capture,
		connectionTypes: renderCheckConnectionTypes(ctx),
	}
	executors, registryErr := buildDirectCheckExecutors(manager, renderer)

	taskGraph := scheduler.NewScheduler(zap.NewNop().Sugar(), pl, assetRenderPreviewRunID)
	for _, instance := range taskGraph.GetTaskInstances() {
		if instance == nil || instance.GetAsset() != asset {
			continue
		}
		if instance.GetType() != scheduler.TaskInstanceTypeColumnCheck && instance.GetType() != scheduler.TaskInstanceTypeCustomCheck {
			continue
		}

		stage := assetRenderCheckStage(instance)
		if registryErr != nil {
			stage.Status = AssetRenderStageStatusError
			stage.Fidelity = AssetRenderFidelityUnsupported
			stage.Message = "check renderer could not be constructed: " + registryErr.Error()
			outcome.stages = append(outcome.stages, stage)
			outcome.issues = append(outcome.issues, AssetRenderIssue{
				Code:     "check_render_failed",
				Severity: "error",
				Message:  stage.Label + ": " + stage.Message,
			})
			outcome.status = AssetRenderStatusPartial
			continue
		}

		configForAsset, assetSupported := executors[asset.Type]
		operator, checkSupported := configForAsset[instance.GetType()]
		if !assetSupported || !checkSupported || operator == nil {
			stage.Status = AssetRenderStageStatusUnsupported
			stage.Fidelity = AssetRenderFidelityUnsupported
			stage.Message = "direct execution does not expose a quality-check operator for this asset type"
			outcome.stages = append(outcome.stages, stage)
			outcome.issues = append(outcome.issues, AssetRenderIssue{
				Code:     "check_render_unsupported",
				Severity: "warning",
				Message:  stage.Label + ": " + stage.Message,
			})
			outcome.status = AssetRenderStatusPartial
			continue
		}

		capture.expected = expectedRenderCheckResult(instance)
		capture.query = ""
		runErr := operator.Run(ctx, instance)
		stage.Content = executedRenderCheckQuery(instance)
		if errors.Is(runErr, errDirectCheckDestinationUnsupported) {
			stage.Status = AssetRenderStageStatusUnsupported
			stage.Fidelity = AssetRenderFidelityUnsupported
			stage.Message = runErr.Error()
			outcome.issues = append(outcome.issues, AssetRenderIssue{
				Code:     "check_render_unsupported",
				Severity: "warning",
				Message:  stage.Label + ": " + stage.Message,
			})
			outcome.status = AssetRenderStatusPartial
		} else if runErr != nil {
			stage.Status = AssetRenderStageStatusError
			if stage.Content != "" {
				stage.Fidelity = AssetRenderFidelityExact
			} else {
				stage.Fidelity = AssetRenderFidelityUnsupported
			}
			stage.Message = "check could not be rendered: " + templateErrorMessage(runErr)
			outcome.issues = append(outcome.issues, AssetRenderIssue{
				Code:     "check_render_failed",
				Severity: "error",
				Message:  stage.Label + ": " + stage.Message,
			})
			outcome.status = AssetRenderStatusPartial
		} else if stage.Content == "" || capture.query == "" {
			stage.Status = AssetRenderStageStatusUnsupported
			stage.Fidelity = AssetRenderFidelityUnsupported
			stage.Message = "the configured check operator did not expose its submitted query"
			outcome.issues = append(outcome.issues, AssetRenderIssue{
				Code:     "check_render_unsupported",
				Severity: "warning",
				Message:  stage.Label + ": " + stage.Message,
			})
			outcome.status = AssetRenderStatusPartial
		} else {
			stage.Status = AssetRenderStageStatusOK
			stage.Fidelity = AssetRenderFidelityExact
		}
		outcome.stages = append(outcome.stages, stage)
	}

	return outcome
}

func assetHasRuntimeChecks(asset *pipeline.Asset) bool {
	if asset == nil {
		return false
	}
	if len(asset.CustomChecks) > 0 {
		return true
	}
	for _, column := range asset.Columns {
		if len(column.Checks) > 0 {
			return true
		}
	}
	return false
}

func assetRenderCheckStage(instance scheduler.TaskInstance) AssetRenderStage {
	stage := AssetRenderStage{
		Kind:        "check",
		Language:    "sql",
		Conditional: true,
	}
	blocking := instance.Blocking()
	stage.CheckBlocking = &blocking

	switch check := instance.(type) {
	case *scheduler.ColumnCheckInstance:
		stage.CheckKind = "column"
		stage.CheckName = check.Check.Name
		stage.CheckColumn = check.Column.Name
		stage.Label = check.Column.Name + " · " + check.Check.Name
	case *scheduler.CustomCheckInstance:
		stage.CheckKind = "custom"
		stage.CheckName = check.Check.Name
		stage.Label = "Custom · " + check.Check.Name
	default:
		stage.Label = "Quality check"
	}

	mode := "Non-blocking"
	if blocking {
		mode = "Blocking"
	}
	stage.Message = mode + " " + stage.CheckKind + " check; runs after the asset operation succeeds"
	return stage
}

func expectedRenderCheckResult(instance scheduler.TaskInstance) int64 {
	custom, ok := instance.(*scheduler.CustomCheckInstance)
	if !ok || custom.Check == nil {
		return 0
	}
	if custom.Check.Count != nil {
		return *custom.Check.Count
	}
	return custom.Check.Value
}

func executedRenderCheckQuery(instance scheduler.TaskInstance) string {
	switch check := instance.(type) {
	case *scheduler.ColumnCheckInstance:
		return check.ExecutedQuery
	case *scheduler.CustomCheckInstance:
		return check.ExecutedQuery
	default:
		return ""
	}
}
