// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storedb

import (
	"database/sql"
)

type PipelineRun struct {
	ID                       string
	PipelineID               string
	Pipeline                 string
	Environment              string
	Trigger                  string
	Status                   string
	WinStart                 sql.NullString
	WinEnd                   sql.NullString
	StartedAt                sql.NullString
	FinishedAt               sql.NullString
	Error                    sql.NullString
	LogRef                   sql.NullString
	SnapshotVersionID        sql.NullString
	RecoveryPending          int64
	RiverJobID               sql.NullInt64
	FullRefresh              int64
	Backfill                 int64
	SensorMode               string
	ExecutionContextResolved int64
	ExecutionTargetSnapshot  string
}

type PipelineRunLog struct {
	RunID string
	Seq   int64
	At    string
	Line  string
}

type PipelineRunSlot struct {
	SlotKey string
	RunID   string
}

type PipelineRunSpec struct {
	RunID     string
	Version   int64
	Body      string
	CreatedAt string
}

type PipelineRunStep struct {
	RunID                  string
	Asset                  string
	Status                 string
	StartedAt              sql.NullString
	FinishedAt             sql.NullString
	Error                  sql.NullString
	CompletionOrdinal      sql.NullInt64
	UpstreamWriterSnapshot string
}

type PipelineScheduleSetting struct {
	PipelineID string
	Enabled    int64
	UpdatedAt  string
}

type RenartAssetRun struct {
	AssetID     string
	Environment string
	Fingerprint string
	Status      string
	RunID       string
	RanAt       string
}

type RenartBlob struct {
	Hash    string
	Content []byte
}

type RenartCompletionOutbox struct {
	Sequence     int64
	CompletionID string
	Version      int64
	Body         string
	EnqueuedAt   string
}

type RenartCoverage struct {
	AssetID          string
	Environment      string
	Fingerprint      string
	VarsHash         string
	TargetIdentity   string
	TargetGeneration int64
	IntervalStart    string
	IntervalEnd      string
	MaterializedAt   string
	OwnContent       string
}

type RenartLatestSuccessfulWriter struct {
	TargetIdentity    string
	TargetGeneration  int64
	AssetID           string
	Environment       string
	Fingerprint       string
	VarsHash          string
	RunID             string
	MaterializedAt    string
	CompletionID      string
	CompletionOrdinal int64
	Ambiguous         int64
}

type RenartMaterialization struct {
	ID                int64
	AssetID           string
	Environment       string
	Fingerprint       string
	VarsHash          string
	IntervalStart     string
	IntervalEnd       string
	RunID             string
	MaterializedAt    string
	OwnContent        string
	TargetIdentity    string
	TargetGeneration  int64
	CompletionID      string
	CompletionOrdinal int64
}

type RenartSchedule struct {
	PipelineID        string
	Environment       string
	SnapshotVersionID string
	Cron              string
	Timezone          string
	Vars              sql.NullString
	CatchupPolicy     string
	Status            string
	ArchivedReason    string
	NextRunAt         sql.NullString
	CreatedAt         string
	UpdatedAt         string
}

type RenartSnapshot struct {
	VersionID          string
	PipelineID         string
	MerkleRoot         string
	Manifest           string
	DependencyManifest string
	GitSha             sql.NullString
	GitDirty           sql.NullInt64
	CreatedAt          string
	CreatedBy          sql.NullString
}

type RenartTargetWriteClaim struct {
	ClaimSequence  int64
	TargetIdentity string
	CompletionID   string
	AssetID        string
	State          string
	ClaimedAt      string
	UpdatedAt      string
}

type ScheduleWatermark struct {
	Pipeline string
	UpTo     string
}
