/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding.success'
import { Route as OnboardingQuickstartRouteImport } from './routes/onboarding/quickstart'
import { Route as OnboardingImportRouteRouteImport } from './routes/onboarding/import/route'
import { Route as WorkspaceSettingsRouteRouteImport } from './routes/_workspace/settings/route'
import { Route as OnboardingImportIndexRouteImport } from './routes/onboarding/import/index'
import { Route as WorkspaceSettingsIndexRouteImport } from './routes/_workspace/settings/index'
import { Route as OnboardingImportReviewRouteImport } from './routes/onboarding/import/review'
import { Route as OnboardingImportConnectionRouteImport } from './routes/onboarding/import/connection'
import { Route as WorkspaceSettingsEnvironmentsRouteRouteImport } from './routes/_workspace/settings/environments/route'
import { Route as WorkspacePipelinesPipelineIdRouteRouteImport } from './routes/_workspace/pipelines/$pipelineId/route'
import { Route as WorkspaceSettingsEnvironmentsIndexRouteImport } from './routes/_workspace/settings/environments/index'
import { Route as WorkspaceSettingsEnvironmentsNewRouteImport } from './routes/_workspace/settings/environments/new'
import { Route as WorkspaceSettingsEnvironmentsEnvironmentIdRouteRouteImport } from './routes/_workspace/settings/environments/$environmentId/route'
import { Route as WorkspacePipelinesPipelineIdConfigRouteRouteImport } from './routes/_workspace/pipelines/$pipelineId/config/route'
import { Route as WorkspaceSettingsEnvironmentsEnvironmentIdIndexRouteImport } from './routes/_workspace/settings/environments/$environmentId/index'
import { Route as WorkspacePipelinesPipelineIdConfigIndexRouteImport } from './routes/_workspace/pipelines/$pipelineId/config/index'
import { Route as WorkspaceSettingsEnvironmentsEnvironmentIdEditRouteImport } from './routes/_workspace/settings/environments/$environmentId/edit'
import { Route as WorkspacePipelinesPipelineIdConfigVariablesRouteImport } from './routes/_workspace/pipelines/$pipelineId/config/variables'
import { Route as WorkspacePipelinesPipelineIdConfigPreviewRouteImport } from './routes/_workspace/pipelines/$pipelineId/config/preview'
import { Route as WorkspacePipelinesPipelineIdConfigNotificationsRouteImport } from './routes/_workspace/pipelines/$pipelineId/config/notifications'
import { Route as WorkspacePipelinesPipelineIdConfigGeneralRouteImport } from './routes/_workspace/pipelines/$pipelineId/config/general'
import { Route as WorkspacePipelinesPipelineIdConfigExecutionRouteImport } from './routes/_workspace/pipelines/$pipelineId/config/execution'
import { Route as WorkspacePipelinesPipelineIdConfigConnectionsRouteImport } from './routes/_workspace/pipelines/$pipelineId/config/connections'
import { Route as WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRouteImport } from './routes/_workspace/settings/environments/$environmentId/connections/route'
import { Route as WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsNewRouteImport } from './routes/_workspace/settings/environments/$environmentId/connections/new'
import { Route as WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRouteImport } from './routes/_workspace/settings/environments/$environmentId/connections/$connectionId/route'
import { Route as WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdIndexRouteImport } from './routes/_workspace/settings/environments/$environmentId/connections/$connectionId/index'
import { Route as WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdEditRouteImport } from './routes/_workspace/settings/environments/$environmentId/connections/$connectionId/edit'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingQuickstartRoute = OnboardingQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingImportRouteRoute = OnboardingImportRouteRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const WorkspaceSettingsRouteRoute = WorkspaceSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const OnboardingImportIndexRoute = OnboardingImportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingImportRouteRoute,
} as any)
const WorkspaceSettingsIndexRoute = WorkspaceSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSettingsRouteRoute,
} as any)
const OnboardingImportReviewRoute = OnboardingImportReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => OnboardingImportRouteRoute,
} as any)
const OnboardingImportConnectionRoute =
  OnboardingImportConnectionRouteImport.update({
    id: '/connection',
    path: '/connection',
    getParentRoute: () => OnboardingImportRouteRoute,
  } as any)
const WorkspaceSettingsEnvironmentsRouteRoute =
  WorkspaceSettingsEnvironmentsRouteRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspacePipelinesPipelineIdRouteRoute =
  WorkspacePipelinesPipelineIdRouteRouteImport.update({
    id: '/pipelines/$pipelineId',
    path: '/pipelines/$pipelineId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceSettingsEnvironmentsIndexRoute =
  WorkspaceSettingsEnvironmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceSettingsEnvironmentsRouteRoute,
  } as any)
const WorkspaceSettingsEnvironmentsNewRoute =
  WorkspaceSettingsEnvironmentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => WorkspaceSettingsEnvironmentsRouteRoute,
  } as any)
const WorkspaceSettingsEnvironmentsEnvironmentIdRouteRoute =
  WorkspaceSettingsEnvironmentsEnvironmentIdRouteRouteImport.update({
    id: '/$environmentId',
    path: '/$environmentId',
    getParentRoute: () => WorkspaceSettingsEnvironmentsRouteRoute,
  } as any)
const WorkspacePipelinesPipelineIdConfigRouteRoute =
  WorkspacePipelinesPipelineIdConfigRouteRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => WorkspacePipelinesPipelineIdRouteRoute,
  } as any)
const WorkspaceSettingsEnvironmentsEnvironmentIdIndexRoute =
  WorkspaceSettingsEnvironmentsEnvironmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceSettingsEnvironmentsEnvironmentIdRouteRoute,
  } as any)
const WorkspacePipelinesPipelineIdConfigIndexRoute =
  WorkspacePipelinesPipelineIdConfigIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacePipelinesPipelineIdConfigRouteRoute,
  } as any)
const WorkspaceSettingsEnvironmentsEnvironmentIdEditRoute =
  WorkspaceSettingsEnvironmentsEnvironmentIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => WorkspaceSettingsEnvironmentsEnvironmentIdRouteRoute,
  } as any)
const WorkspacePipelinesPipelineIdConfigVariablesRoute =
  WorkspacePipelinesPipelineIdConfigVariablesRouteImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => WorkspacePipelinesPipelineIdConfigRouteRoute,
  } as any)
const WorkspacePipelinesPipelineIdConfigPreviewRoute =
  WorkspacePipelinesPipelineIdConfigPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => WorkspacePipelinesPipelineIdConfigRouteRoute,
  } as any)
const WorkspacePipelinesPipelineIdConfigNotificationsRoute =
  WorkspacePipelinesPipelineIdConfigNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => WorkspacePipelinesPipelineIdConfigRouteRoute,
  } as any)
const WorkspacePipelinesPipelineIdConfigGeneralRoute =
  WorkspacePipelinesPipelineIdConfigGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => WorkspacePipelinesPipelineIdConfigRouteRoute,
  } as any)
const WorkspacePipelinesPipelineIdConfigExecutionRoute =
  WorkspacePipelinesPipelineIdConfigExecutionRouteImport.update({
    id: '/execution',
    path: '/execution',
    getParentRoute: () => WorkspacePipelinesPipelineIdConfigRouteRoute,
  } as any)
const WorkspacePipelinesPipelineIdConfigConnectionsRoute =
  WorkspacePipelinesPipelineIdConfigConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => WorkspacePipelinesPipelineIdConfigRouteRoute,
  } as any)
const WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRoute =
  WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => WorkspaceSettingsEnvironmentsEnvironmentIdRouteRoute,
  } as any)
const WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsNewRoute =
  WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () =>
      WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRoute,
  } as any)
const WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRoute =
  WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRouteImport.update(
    {
      id: '/$connectionId',
      path: '/$connectionId',
      getParentRoute: () =>
        WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRoute,
    } as any,
  )
const WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdIndexRoute =
  WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRoute,
    } as any,
  )
const WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdEditRoute =
  WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdEditRouteImport.update(
    {
      id: '/edit',
      path: '/edit',
      getParentRoute: () =>
        WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/': typeof WorkspaceIndexRoute
  '/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/onboarding/import': typeof OnboardingImportRouteRouteWithChildren
  '/onboarding/quickstart': typeof OnboardingQuickstartRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/pipelines/$pipelineId': typeof WorkspacePipelinesPipelineIdRouteRouteWithChildren
  '/settings/environments': typeof WorkspaceSettingsEnvironmentsRouteRouteWithChildren
  '/onboarding/import/connection': typeof OnboardingImportConnectionRoute
  '/onboarding/import/review': typeof OnboardingImportReviewRoute
  '/settings/': typeof WorkspaceSettingsIndexRoute
  '/onboarding/import/': typeof OnboardingImportIndexRoute
  '/pipelines/$pipelineId/config': typeof WorkspacePipelinesPipelineIdConfigRouteRouteWithChildren
  '/settings/environments/$environmentId': typeof WorkspaceSettingsEnvironmentsEnvironmentIdRouteRouteWithChildren
  '/settings/environments/new': typeof WorkspaceSettingsEnvironmentsNewRoute
  '/settings/environments/': typeof WorkspaceSettingsEnvironmentsIndexRoute
  '/settings/environments/$environmentId/connections': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRouteWithChildren
  '/pipelines/$pipelineId/config/connections': typeof WorkspacePipelinesPipelineIdConfigConnectionsRoute
  '/pipelines/$pipelineId/config/execution': typeof WorkspacePipelinesPipelineIdConfigExecutionRoute
  '/pipelines/$pipelineId/config/general': typeof WorkspacePipelinesPipelineIdConfigGeneralRoute
  '/pipelines/$pipelineId/config/notifications': typeof WorkspacePipelinesPipelineIdConfigNotificationsRoute
  '/pipelines/$pipelineId/config/preview': typeof WorkspacePipelinesPipelineIdConfigPreviewRoute
  '/pipelines/$pipelineId/config/variables': typeof WorkspacePipelinesPipelineIdConfigVariablesRoute
  '/settings/environments/$environmentId/edit': typeof WorkspaceSettingsEnvironmentsEnvironmentIdEditRoute
  '/pipelines/$pipelineId/config/': typeof WorkspacePipelinesPipelineIdConfigIndexRoute
  '/settings/environments/$environmentId/': typeof WorkspaceSettingsEnvironmentsEnvironmentIdIndexRoute
  '/settings/environments/$environmentId/connections/$connectionId': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRouteWithChildren
  '/settings/environments/$environmentId/connections/new': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsNewRoute
  '/settings/environments/$environmentId/connections/$connectionId/edit': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdEditRoute
  '/settings/environments/$environmentId/connections/$connectionId/': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding/quickstart': typeof OnboardingQuickstartRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/': typeof WorkspaceIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/pipelines/$pipelineId': typeof WorkspacePipelinesPipelineIdRouteRouteWithChildren
  '/onboarding/import/connection': typeof OnboardingImportConnectionRoute
  '/onboarding/import/review': typeof OnboardingImportReviewRoute
  '/settings': typeof WorkspaceSettingsIndexRoute
  '/onboarding/import': typeof OnboardingImportIndexRoute
  '/settings/environments/new': typeof WorkspaceSettingsEnvironmentsNewRoute
  '/settings/environments': typeof WorkspaceSettingsEnvironmentsIndexRoute
  '/settings/environments/$environmentId/connections': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRouteWithChildren
  '/pipelines/$pipelineId/config/connections': typeof WorkspacePipelinesPipelineIdConfigConnectionsRoute
  '/pipelines/$pipelineId/config/execution': typeof WorkspacePipelinesPipelineIdConfigExecutionRoute
  '/pipelines/$pipelineId/config/general': typeof WorkspacePipelinesPipelineIdConfigGeneralRoute
  '/pipelines/$pipelineId/config/notifications': typeof WorkspacePipelinesPipelineIdConfigNotificationsRoute
  '/pipelines/$pipelineId/config/preview': typeof WorkspacePipelinesPipelineIdConfigPreviewRoute
  '/pipelines/$pipelineId/config/variables': typeof WorkspacePipelinesPipelineIdConfigVariablesRoute
  '/settings/environments/$environmentId/edit': typeof WorkspaceSettingsEnvironmentsEnvironmentIdEditRoute
  '/pipelines/$pipelineId/config': typeof WorkspacePipelinesPipelineIdConfigIndexRoute
  '/settings/environments/$environmentId': typeof WorkspaceSettingsEnvironmentsEnvironmentIdIndexRoute
  '/settings/environments/$environmentId/connections/new': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsNewRoute
  '/settings/environments/$environmentId/connections/$connectionId/edit': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdEditRoute
  '/settings/environments/$environmentId/connections/$connectionId': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/onboarding/import': typeof OnboardingImportRouteRouteWithChildren
  '/onboarding/quickstart': typeof OnboardingQuickstartRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_workspace/pipelines/$pipelineId': typeof WorkspacePipelinesPipelineIdRouteRouteWithChildren
  '/_workspace/settings/environments': typeof WorkspaceSettingsEnvironmentsRouteRouteWithChildren
  '/onboarding/import/connection': typeof OnboardingImportConnectionRoute
  '/onboarding/import/review': typeof OnboardingImportReviewRoute
  '/_workspace/settings/': typeof WorkspaceSettingsIndexRoute
  '/onboarding/import/': typeof OnboardingImportIndexRoute
  '/_workspace/pipelines/$pipelineId/config': typeof WorkspacePipelinesPipelineIdConfigRouteRouteWithChildren
  '/_workspace/settings/environments/$environmentId': typeof WorkspaceSettingsEnvironmentsEnvironmentIdRouteRouteWithChildren
  '/_workspace/settings/environments/new': typeof WorkspaceSettingsEnvironmentsNewRoute
  '/_workspace/settings/environments/': typeof WorkspaceSettingsEnvironmentsIndexRoute
  '/_workspace/settings/environments/$environmentId/connections': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRouteWithChildren
  '/_workspace/pipelines/$pipelineId/config/connections': typeof WorkspacePipelinesPipelineIdConfigConnectionsRoute
  '/_workspace/pipelines/$pipelineId/config/execution': typeof WorkspacePipelinesPipelineIdConfigExecutionRoute
  '/_workspace/pipelines/$pipelineId/config/general': typeof WorkspacePipelinesPipelineIdConfigGeneralRoute
  '/_workspace/pipelines/$pipelineId/config/notifications': typeof WorkspacePipelinesPipelineIdConfigNotificationsRoute
  '/_workspace/pipelines/$pipelineId/config/preview': typeof WorkspacePipelinesPipelineIdConfigPreviewRoute
  '/_workspace/pipelines/$pipelineId/config/variables': typeof WorkspacePipelinesPipelineIdConfigVariablesRoute
  '/_workspace/settings/environments/$environmentId/edit': typeof WorkspaceSettingsEnvironmentsEnvironmentIdEditRoute
  '/_workspace/pipelines/$pipelineId/config/': typeof WorkspacePipelinesPipelineIdConfigIndexRoute
  '/_workspace/settings/environments/$environmentId/': typeof WorkspaceSettingsEnvironmentsEnvironmentIdIndexRoute
  '/_workspace/settings/environments/$environmentId/connections/$connectionId': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRouteWithChildren
  '/_workspace/settings/environments/$environmentId/connections/new': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsNewRoute
  '/_workspace/settings/environments/$environmentId/connections/$connectionId/edit': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdEditRoute
  '/_workspace/settings/environments/$environmentId/connections/$connectionId/': typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboarding'
    | '/'
    | '/settings'
    | '/onboarding/import'
    | '/onboarding/quickstart'
    | '/onboarding/success'
    | '/onboarding/'
    | '/pipelines/$pipelineId'
    | '/settings/environments'
    | '/onboarding/import/connection'
    | '/onboarding/import/review'
    | '/settings/'
    | '/onboarding/import/'
    | '/pipelines/$pipelineId/config'
    | '/settings/environments/$environmentId'
    | '/settings/environments/new'
    | '/settings/environments/'
    | '/settings/environments/$environmentId/connections'
    | '/pipelines/$pipelineId/config/connections'
    | '/pipelines/$pipelineId/config/execution'
    | '/pipelines/$pipelineId/config/general'
    | '/pipelines/$pipelineId/config/notifications'
    | '/pipelines/$pipelineId/config/preview'
    | '/pipelines/$pipelineId/config/variables'
    | '/settings/environments/$environmentId/edit'
    | '/pipelines/$pipelineId/config/'
    | '/settings/environments/$environmentId/'
    | '/settings/environments/$environmentId/connections/$connectionId'
    | '/settings/environments/$environmentId/connections/new'
    | '/settings/environments/$environmentId/connections/$connectionId/edit'
    | '/settings/environments/$environmentId/connections/$connectionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding/quickstart'
    | '/onboarding/success'
    | '/'
    | '/onboarding'
    | '/pipelines/$pipelineId'
    | '/onboarding/import/connection'
    | '/onboarding/import/review'
    | '/settings'
    | '/onboarding/import'
    | '/settings/environments/new'
    | '/settings/environments'
    | '/settings/environments/$environmentId/connections'
    | '/pipelines/$pipelineId/config/connections'
    | '/pipelines/$pipelineId/config/execution'
    | '/pipelines/$pipelineId/config/general'
    | '/pipelines/$pipelineId/config/notifications'
    | '/pipelines/$pipelineId/config/preview'
    | '/pipelines/$pipelineId/config/variables'
    | '/settings/environments/$environmentId/edit'
    | '/pipelines/$pipelineId/config'
    | '/settings/environments/$environmentId'
    | '/settings/environments/$environmentId/connections/new'
    | '/settings/environments/$environmentId/connections/$connectionId/edit'
    | '/settings/environments/$environmentId/connections/$connectionId'
  id:
    | '__root__'
    | '/onboarding'
    | '/_workspace'
    | '/_workspace/settings'
    | '/onboarding/import'
    | '/onboarding/quickstart'
    | '/onboarding/success'
    | '/_workspace/'
    | '/onboarding/'
    | '/_workspace/pipelines/$pipelineId'
    | '/_workspace/settings/environments'
    | '/onboarding/import/connection'
    | '/onboarding/import/review'
    | '/_workspace/settings/'
    | '/onboarding/import/'
    | '/_workspace/pipelines/$pipelineId/config'
    | '/_workspace/settings/environments/$environmentId'
    | '/_workspace/settings/environments/new'
    | '/_workspace/settings/environments/'
    | '/_workspace/settings/environments/$environmentId/connections'
    | '/_workspace/pipelines/$pipelineId/config/connections'
    | '/_workspace/pipelines/$pipelineId/config/execution'
    | '/_workspace/pipelines/$pipelineId/config/general'
    | '/_workspace/pipelines/$pipelineId/config/notifications'
    | '/_workspace/pipelines/$pipelineId/config/preview'
    | '/_workspace/pipelines/$pipelineId/config/variables'
    | '/_workspace/settings/environments/$environmentId/edit'
    | '/_workspace/pipelines/$pipelineId/config/'
    | '/_workspace/settings/environments/$environmentId/'
    | '/_workspace/settings/environments/$environmentId/connections/$connectionId'
    | '/_workspace/settings/environments/$environmentId/connections/new'
    | '/_workspace/settings/environments/$environmentId/connections/$connectionId/edit'
    | '/_workspace/settings/environments/$environmentId/connections/$connectionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/onboarding/success': {
      id: '/onboarding/success'
      path: '/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/quickstart': {
      id: '/onboarding/quickstart'
      path: '/quickstart'
      fullPath: '/onboarding/quickstart'
      preLoaderRoute: typeof OnboardingQuickstartRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/import': {
      id: '/onboarding/import'
      path: '/import'
      fullPath: '/onboarding/import'
      preLoaderRoute: typeof OnboardingImportRouteRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/onboarding/import/': {
      id: '/onboarding/import/'
      path: '/'
      fullPath: '/onboarding/import/'
      preLoaderRoute: typeof OnboardingImportIndexRouteImport
      parentRoute: typeof OnboardingImportRouteRoute
    }
    '/_workspace/settings/': {
      id: '/_workspace/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof WorkspaceSettingsIndexRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/onboarding/import/review': {
      id: '/onboarding/import/review'
      path: '/review'
      fullPath: '/onboarding/import/review'
      preLoaderRoute: typeof OnboardingImportReviewRouteImport
      parentRoute: typeof OnboardingImportRouteRoute
    }
    '/onboarding/import/connection': {
      id: '/onboarding/import/connection'
      path: '/connection'
      fullPath: '/onboarding/import/connection'
      preLoaderRoute: typeof OnboardingImportConnectionRouteImport
      parentRoute: typeof OnboardingImportRouteRoute
    }
    '/_workspace/settings/environments': {
      id: '/_workspace/settings/environments'
      path: '/environments'
      fullPath: '/settings/environments'
      preLoaderRoute: typeof WorkspaceSettingsEnvironmentsRouteRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/pipelines/$pipelineId': {
      id: '/_workspace/pipelines/$pipelineId'
      path: '/pipelines/$pipelineId'
      fullPath: '/pipelines/$pipelineId'
      preLoaderRoute: typeof WorkspacePipelinesPipelineIdRouteRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings/environments/': {
      id: '/_workspace/settings/environments/'
      path: '/'
      fullPath: '/settings/environments/'
      preLoaderRoute: typeof WorkspaceSettingsEnvironmentsIndexRouteImport
      parentRoute: typeof WorkspaceSettingsEnvironmentsRouteRoute
    }
    '/_workspace/settings/environments/new': {
      id: '/_workspace/settings/environments/new'
      path: '/new'
      fullPath: '/settings/environments/new'
      preLoaderRoute: typeof WorkspaceSettingsEnvironmentsNewRouteImport
      parentRoute: typeof WorkspaceSettingsEnvironmentsRouteRoute
    }
    '/_workspace/settings/environments/$environmentId': {
      id: '/_workspace/settings/environments/$environmentId'
      path: '/$environmentId'
      fullPath: '/settings/environments/$environmentId'
      preLoaderRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdRouteRouteImport
      parentRoute: typeof WorkspaceSettingsEnvironmentsRouteRoute
    }
    '/_workspace/pipelines/$pipelineId/config': {
      id: '/_workspace/pipelines/$pipelineId/config'
      path: '/config'
      fullPath: '/pipelines/$pipelineId/config'
      preLoaderRoute: typeof WorkspacePipelinesPipelineIdConfigRouteRouteImport
      parentRoute: typeof WorkspacePipelinesPipelineIdRouteRoute
    }
    '/_workspace/settings/environments/$environmentId/': {
      id: '/_workspace/settings/environments/$environmentId/'
      path: '/'
      fullPath: '/settings/environments/$environmentId/'
      preLoaderRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdIndexRouteImport
      parentRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdRouteRoute
    }
    '/_workspace/pipelines/$pipelineId/config/': {
      id: '/_workspace/pipelines/$pipelineId/config/'
      path: '/'
      fullPath: '/pipelines/$pipelineId/config/'
      preLoaderRoute: typeof WorkspacePipelinesPipelineIdConfigIndexRouteImport
      parentRoute: typeof WorkspacePipelinesPipelineIdConfigRouteRoute
    }
    '/_workspace/settings/environments/$environmentId/edit': {
      id: '/_workspace/settings/environments/$environmentId/edit'
      path: '/edit'
      fullPath: '/settings/environments/$environmentId/edit'
      preLoaderRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdEditRouteImport
      parentRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdRouteRoute
    }
    '/_workspace/pipelines/$pipelineId/config/variables': {
      id: '/_workspace/pipelines/$pipelineId/config/variables'
      path: '/variables'
      fullPath: '/pipelines/$pipelineId/config/variables'
      preLoaderRoute: typeof WorkspacePipelinesPipelineIdConfigVariablesRouteImport
      parentRoute: typeof WorkspacePipelinesPipelineIdConfigRouteRoute
    }
    '/_workspace/pipelines/$pipelineId/config/preview': {
      id: '/_workspace/pipelines/$pipelineId/config/preview'
      path: '/preview'
      fullPath: '/pipelines/$pipelineId/config/preview'
      preLoaderRoute: typeof WorkspacePipelinesPipelineIdConfigPreviewRouteImport
      parentRoute: typeof WorkspacePipelinesPipelineIdConfigRouteRoute
    }
    '/_workspace/pipelines/$pipelineId/config/notifications': {
      id: '/_workspace/pipelines/$pipelineId/config/notifications'
      path: '/notifications'
      fullPath: '/pipelines/$pipelineId/config/notifications'
      preLoaderRoute: typeof WorkspacePipelinesPipelineIdConfigNotificationsRouteImport
      parentRoute: typeof WorkspacePipelinesPipelineIdConfigRouteRoute
    }
    '/_workspace/pipelines/$pipelineId/config/general': {
      id: '/_workspace/pipelines/$pipelineId/config/general'
      path: '/general'
      fullPath: '/pipelines/$pipelineId/config/general'
      preLoaderRoute: typeof WorkspacePipelinesPipelineIdConfigGeneralRouteImport
      parentRoute: typeof WorkspacePipelinesPipelineIdConfigRouteRoute
    }
    '/_workspace/pipelines/$pipelineId/config/execution': {
      id: '/_workspace/pipelines/$pipelineId/config/execution'
      path: '/execution'
      fullPath: '/pipelines/$pipelineId/config/execution'
      preLoaderRoute: typeof WorkspacePipelinesPipelineIdConfigExecutionRouteImport
      parentRoute: typeof WorkspacePipelinesPipelineIdConfigRouteRoute
    }
    '/_workspace/pipelines/$pipelineId/config/connections': {
      id: '/_workspace/pipelines/$pipelineId/config/connections'
      path: '/connections'
      fullPath: '/pipelines/$pipelineId/config/connections'
      preLoaderRoute: typeof WorkspacePipelinesPipelineIdConfigConnectionsRouteImport
      parentRoute: typeof WorkspacePipelinesPipelineIdConfigRouteRoute
    }
    '/_workspace/settings/environments/$environmentId/connections': {
      id: '/_workspace/settings/environments/$environmentId/connections'
      path: '/connections'
      fullPath: '/settings/environments/$environmentId/connections'
      preLoaderRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRouteImport
      parentRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdRouteRoute
    }
    '/_workspace/settings/environments/$environmentId/connections/new': {
      id: '/_workspace/settings/environments/$environmentId/connections/new'
      path: '/new'
      fullPath: '/settings/environments/$environmentId/connections/new'
      preLoaderRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsNewRouteImport
      parentRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRoute
    }
    '/_workspace/settings/environments/$environmentId/connections/$connectionId': {
      id: '/_workspace/settings/environments/$environmentId/connections/$connectionId'
      path: '/$connectionId'
      fullPath: '/settings/environments/$environmentId/connections/$connectionId'
      preLoaderRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRouteImport
      parentRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRoute
    }
    '/_workspace/settings/environments/$environmentId/connections/$connectionId/': {
      id: '/_workspace/settings/environments/$environmentId/connections/$connectionId/'
      path: '/'
      fullPath: '/settings/environments/$environmentId/connections/$connectionId/'
      preLoaderRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdIndexRouteImport
      parentRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRoute
    }
    '/_workspace/settings/environments/$environmentId/connections/$connectionId/edit': {
      id: '/_workspace/settings/environments/$environmentId/connections/$connectionId/edit'
      path: '/edit'
      fullPath: '/settings/environments/$environmentId/connections/$connectionId/edit'
      preLoaderRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdEditRouteImport
      parentRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRoute
    }
  }
}

interface OnboardingImportRouteRouteChildren {
  OnboardingImportConnectionRoute: typeof OnboardingImportConnectionRoute
  OnboardingImportReviewRoute: typeof OnboardingImportReviewRoute
  OnboardingImportIndexRoute: typeof OnboardingImportIndexRoute
}

const OnboardingImportRouteRouteChildren: OnboardingImportRouteRouteChildren = {
  OnboardingImportConnectionRoute: OnboardingImportConnectionRoute,
  OnboardingImportReviewRoute: OnboardingImportReviewRoute,
  OnboardingImportIndexRoute: OnboardingImportIndexRoute,
}

const OnboardingImportRouteRouteWithChildren =
  OnboardingImportRouteRoute._addFileChildren(
    OnboardingImportRouteRouteChildren,
  )

interface OnboardingRouteRouteChildren {
  OnboardingImportRouteRoute: typeof OnboardingImportRouteRouteWithChildren
  OnboardingQuickstartRoute: typeof OnboardingQuickstartRoute
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingImportRouteRoute: OnboardingImportRouteRouteWithChildren,
  OnboardingQuickstartRoute: OnboardingQuickstartRoute,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRouteChildren {
  WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdEditRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdEditRoute
  WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdIndexRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdIndexRoute
}

const WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRouteChildren: WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRouteChildren =
  {
    WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdEditRoute:
      WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdEditRoute,
    WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdIndexRoute:
      WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdIndexRoute,
  }

const WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRouteWithChildren =
  WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRoute._addFileChildren(
    WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRouteChildren,
  )

interface WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRouteChildren {
  WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRouteWithChildren
  WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsNewRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsNewRoute
}

const WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRouteChildren: WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRouteChildren =
  {
    WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRoute:
      WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsConnectionIdRouteRouteWithChildren,
    WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsNewRoute:
      WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsNewRoute,
  }

const WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRouteWithChildren =
  WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRoute._addFileChildren(
    WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRouteChildren,
  )

interface WorkspaceSettingsEnvironmentsEnvironmentIdRouteRouteChildren {
  WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRouteWithChildren
  WorkspaceSettingsEnvironmentsEnvironmentIdEditRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdEditRoute
  WorkspaceSettingsEnvironmentsEnvironmentIdIndexRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdIndexRoute
}

const WorkspaceSettingsEnvironmentsEnvironmentIdRouteRouteChildren: WorkspaceSettingsEnvironmentsEnvironmentIdRouteRouteChildren =
  {
    WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRoute:
      WorkspaceSettingsEnvironmentsEnvironmentIdConnectionsRouteRouteWithChildren,
    WorkspaceSettingsEnvironmentsEnvironmentIdEditRoute:
      WorkspaceSettingsEnvironmentsEnvironmentIdEditRoute,
    WorkspaceSettingsEnvironmentsEnvironmentIdIndexRoute:
      WorkspaceSettingsEnvironmentsEnvironmentIdIndexRoute,
  }

const WorkspaceSettingsEnvironmentsEnvironmentIdRouteRouteWithChildren =
  WorkspaceSettingsEnvironmentsEnvironmentIdRouteRoute._addFileChildren(
    WorkspaceSettingsEnvironmentsEnvironmentIdRouteRouteChildren,
  )

interface WorkspaceSettingsEnvironmentsRouteRouteChildren {
  WorkspaceSettingsEnvironmentsEnvironmentIdRouteRoute: typeof WorkspaceSettingsEnvironmentsEnvironmentIdRouteRouteWithChildren
  WorkspaceSettingsEnvironmentsNewRoute: typeof WorkspaceSettingsEnvironmentsNewRoute
  WorkspaceSettingsEnvironmentsIndexRoute: typeof WorkspaceSettingsEnvironmentsIndexRoute
}

const WorkspaceSettingsEnvironmentsRouteRouteChildren: WorkspaceSettingsEnvironmentsRouteRouteChildren =
  {
    WorkspaceSettingsEnvironmentsEnvironmentIdRouteRoute:
      WorkspaceSettingsEnvironmentsEnvironmentIdRouteRouteWithChildren,
    WorkspaceSettingsEnvironmentsNewRoute:
      WorkspaceSettingsEnvironmentsNewRoute,
    WorkspaceSettingsEnvironmentsIndexRoute:
      WorkspaceSettingsEnvironmentsIndexRoute,
  }

const WorkspaceSettingsEnvironmentsRouteRouteWithChildren =
  WorkspaceSettingsEnvironmentsRouteRoute._addFileChildren(
    WorkspaceSettingsEnvironmentsRouteRouteChildren,
  )

interface WorkspaceSettingsRouteRouteChildren {
  WorkspaceSettingsEnvironmentsRouteRoute: typeof WorkspaceSettingsEnvironmentsRouteRouteWithChildren
  WorkspaceSettingsIndexRoute: typeof WorkspaceSettingsIndexRoute
}

const WorkspaceSettingsRouteRouteChildren: WorkspaceSettingsRouteRouteChildren =
  {
    WorkspaceSettingsEnvironmentsRouteRoute:
      WorkspaceSettingsEnvironmentsRouteRouteWithChildren,
    WorkspaceSettingsIndexRoute: WorkspaceSettingsIndexRoute,
  }

const WorkspaceSettingsRouteRouteWithChildren =
  WorkspaceSettingsRouteRoute._addFileChildren(
    WorkspaceSettingsRouteRouteChildren,
  )

interface WorkspacePipelinesPipelineIdConfigRouteRouteChildren {
  WorkspacePipelinesPipelineIdConfigConnectionsRoute: typeof WorkspacePipelinesPipelineIdConfigConnectionsRoute
  WorkspacePipelinesPipelineIdConfigExecutionRoute: typeof WorkspacePipelinesPipelineIdConfigExecutionRoute
  WorkspacePipelinesPipelineIdConfigGeneralRoute: typeof WorkspacePipelinesPipelineIdConfigGeneralRoute
  WorkspacePipelinesPipelineIdConfigNotificationsRoute: typeof WorkspacePipelinesPipelineIdConfigNotificationsRoute
  WorkspacePipelinesPipelineIdConfigPreviewRoute: typeof WorkspacePipelinesPipelineIdConfigPreviewRoute
  WorkspacePipelinesPipelineIdConfigVariablesRoute: typeof WorkspacePipelinesPipelineIdConfigVariablesRoute
  WorkspacePipelinesPipelineIdConfigIndexRoute: typeof WorkspacePipelinesPipelineIdConfigIndexRoute
}

const WorkspacePipelinesPipelineIdConfigRouteRouteChildren: WorkspacePipelinesPipelineIdConfigRouteRouteChildren =
  {
    WorkspacePipelinesPipelineIdConfigConnectionsRoute:
      WorkspacePipelinesPipelineIdConfigConnectionsRoute,
    WorkspacePipelinesPipelineIdConfigExecutionRoute:
      WorkspacePipelinesPipelineIdConfigExecutionRoute,
    WorkspacePipelinesPipelineIdConfigGeneralRoute:
      WorkspacePipelinesPipelineIdConfigGeneralRoute,
    WorkspacePipelinesPipelineIdConfigNotificationsRoute:
      WorkspacePipelinesPipelineIdConfigNotificationsRoute,
    WorkspacePipelinesPipelineIdConfigPreviewRoute:
      WorkspacePipelinesPipelineIdConfigPreviewRoute,
    WorkspacePipelinesPipelineIdConfigVariablesRoute:
      WorkspacePipelinesPipelineIdConfigVariablesRoute,
    WorkspacePipelinesPipelineIdConfigIndexRoute:
      WorkspacePipelinesPipelineIdConfigIndexRoute,
  }

const WorkspacePipelinesPipelineIdConfigRouteRouteWithChildren =
  WorkspacePipelinesPipelineIdConfigRouteRoute._addFileChildren(
    WorkspacePipelinesPipelineIdConfigRouteRouteChildren,
  )

interface WorkspacePipelinesPipelineIdRouteRouteChildren {
  WorkspacePipelinesPipelineIdConfigRouteRoute: typeof WorkspacePipelinesPipelineIdConfigRouteRouteWithChildren
}

const WorkspacePipelinesPipelineIdRouteRouteChildren: WorkspacePipelinesPipelineIdRouteRouteChildren =
  {
    WorkspacePipelinesPipelineIdConfigRouteRoute:
      WorkspacePipelinesPipelineIdConfigRouteRouteWithChildren,
  }

const WorkspacePipelinesPipelineIdRouteRouteWithChildren =
  WorkspacePipelinesPipelineIdRouteRoute._addFileChildren(
    WorkspacePipelinesPipelineIdRouteRouteChildren,
  )

interface WorkspaceRouteChildren {
  WorkspaceSettingsRouteRoute: typeof WorkspaceSettingsRouteRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspacePipelinesPipelineIdRouteRoute: typeof WorkspacePipelinesPipelineIdRouteRouteWithChildren
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceSettingsRouteRoute: WorkspaceSettingsRouteRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspacePipelinesPipelineIdRouteRoute:
    WorkspacePipelinesPipelineIdRouteRouteWithChildren,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
