/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as RedesignIndexRouteImport } from './routes/redesign.index'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as RedesignSplatRouteImport } from './routes/redesign.$'
import { Route as ShellCatalogRouteImport } from './routes/_shell/catalog'
import { Route as ShellSchedulesRouteRouteImport } from './routes/_shell/schedules/route'
import { Route as ShellRunsRouteRouteImport } from './routes/_shell/runs/route'
import { Route as ShellProjectRouteRouteImport } from './routes/_shell/project/route'
import { Route as ShellPresentationsRouteRouteImport } from './routes/_shell/_presentations/route'
import { Route as ShellSchedulesIndexRouteImport } from './routes/_shell/schedules/index'
import { Route as ShellRunsIndexRouteImport } from './routes/_shell/runs/index'
import { Route as ShellProjectIndexRouteImport } from './routes/_shell/project/index'
import { Route as ShellNotebooksIndexRouteImport } from './routes/_shell/notebooks/index'
import { Route as ShellSchedulesTimelineRouteImport } from './routes/_shell/schedules/timeline'
import { Route as ShellSchedulesDeploymentsRouteImport } from './routes/_shell/schedules/deployments'
import { Route as ShellRunsRunIdRouteImport } from './routes/_shell/runs/$runId'
import { Route as ShellProjectGeneralRouteImport } from './routes/_shell/project/general'
import { Route as ShellProjectEnvironmentsRouteImport } from './routes/_shell/project/environments'
import { Route as ShellProjectConnectionsRouteImport } from './routes/_shell/project/connections'
import { Route as ShellNotebooksNotebookIdRouteImport } from './routes/_shell/notebooks/$notebookId'
import { Route as ShellPipelinesPipelineIdRouteRouteImport } from './routes/_shell/pipelines/$pipelineId/route'
import { Route as ShellPipelinesPipelineIdIndexRouteImport } from './routes/_shell/pipelines/$pipelineId/index'
import { Route as ShellPresentationsReportsIndexRouteImport } from './routes/_shell/_presentations/reports/index'
import { Route as ShellPresentationsDashboardsIndexRouteImport } from './routes/_shell/_presentations/dashboards/index'
import { Route as ShellPipelinesPipelineIdSplitRouteImport } from './routes/_shell/pipelines/$pipelineId/split'
import { Route as ShellPipelinesPipelineIdCodeRouteImport } from './routes/_shell/pipelines/$pipelineId/code'
import { Route as ShellPipelinesPipelineIdCanvasRouteImport } from './routes/_shell/pipelines/$pipelineId/canvas'
import { Route as ShellPresentationsReportsPresentationIdRouteRouteImport } from './routes/_shell/_presentations/reports/$presentationId/route'
import { Route as ShellPresentationsDashboardsPresentationIdRouteRouteImport } from './routes/_shell/_presentations/dashboards/$presentationId/route'
import { Route as ShellPresentationsReportsPresentationIdIndexRouteImport } from './routes/_shell/_presentations/reports/$presentationId/index'
import { Route as ShellPresentationsDashboardsPresentationIdIndexRouteImport } from './routes/_shell/_presentations/dashboards/$presentationId/index'
import { Route as ShellPresentationsReportsPresentationIdViewRouteImport } from './routes/_shell/_presentations/reports/$presentationId/view'
import { Route as ShellPresentationsDashboardsPresentationIdViewRouteImport } from './routes/_shell/_presentations/dashboards/$presentationId/view'
import { Route as ShellPipelinesPipelineIdAssetsAssetIdRouteRouteImport } from './routes/_shell/pipelines/$pipelineId/assets/$assetId/route'
import { Route as ShellPipelinesPipelineIdAssetsAssetIdIndexRouteImport } from './routes/_shell/pipelines/$pipelineId/assets/$assetId/index'
import { Route as ShellPipelinesPipelineIdAssetsAssetIdSplitRouteImport } from './routes/_shell/pipelines/$pipelineId/assets/$assetId/split'
import { Route as ShellPipelinesPipelineIdAssetsAssetIdCodeRouteImport } from './routes/_shell/pipelines/$pipelineId/assets/$assetId/code'
import { Route as ShellPipelinesPipelineIdAssetsAssetIdCanvasRouteImport } from './routes/_shell/pipelines/$pipelineId/assets/$assetId/canvas'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesignIndexRoute = RedesignIndexRouteImport.update({
  id: '/redesign/',
  path: '/redesign/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const RedesignSplatRoute = RedesignSplatRouteImport.update({
  id: '/redesign/$',
  path: '/redesign/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCatalogRoute = ShellCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSchedulesRouteRoute = ShellSchedulesRouteRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRunsRouteRoute = ShellRunsRouteRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectRouteRoute = ShellProjectRouteRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPresentationsRouteRoute = ShellPresentationsRouteRouteImport.update({
  id: '/_presentations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSchedulesIndexRoute = ShellSchedulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellSchedulesRouteRoute,
} as any)
const ShellRunsIndexRoute = ShellRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRunsRouteRoute,
} as any)
const ShellProjectIndexRoute = ShellProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellProjectRouteRoute,
} as any)
const ShellNotebooksIndexRoute = ShellNotebooksIndexRouteImport.update({
  id: '/notebooks/',
  path: '/notebooks/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSchedulesTimelineRoute = ShellSchedulesTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ShellSchedulesRouteRoute,
} as any)
const ShellSchedulesDeploymentsRoute =
  ShellSchedulesDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => ShellSchedulesRouteRoute,
  } as any)
const ShellRunsRunIdRoute = ShellRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => ShellRunsRouteRoute,
} as any)
const ShellProjectGeneralRoute = ShellProjectGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => ShellProjectRouteRoute,
} as any)
const ShellProjectEnvironmentsRoute =
  ShellProjectEnvironmentsRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => ShellProjectRouteRoute,
  } as any)
const ShellProjectConnectionsRoute = ShellProjectConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => ShellProjectRouteRoute,
} as any)
const ShellNotebooksNotebookIdRoute =
  ShellNotebooksNotebookIdRouteImport.update({
    id: '/notebooks/$notebookId',
    path: '/notebooks/$notebookId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellPipelinesPipelineIdRouteRoute =
  ShellPipelinesPipelineIdRouteRouteImport.update({
    id: '/pipelines/$pipelineId',
    path: '/pipelines/$pipelineId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellPipelinesPipelineIdIndexRoute =
  ShellPipelinesPipelineIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellPipelinesPipelineIdRouteRoute,
  } as any)
const ShellPresentationsReportsIndexRoute =
  ShellPresentationsReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => ShellPresentationsRouteRoute,
  } as any)
const ShellPresentationsDashboardsIndexRoute =
  ShellPresentationsDashboardsIndexRouteImport.update({
    id: '/dashboards/',
    path: '/dashboards/',
    getParentRoute: () => ShellPresentationsRouteRoute,
  } as any)
const ShellPipelinesPipelineIdSplitRoute =
  ShellPipelinesPipelineIdSplitRouteImport.update({
    id: '/split',
    path: '/split',
    getParentRoute: () => ShellPipelinesPipelineIdRouteRoute,
  } as any)
const ShellPipelinesPipelineIdCodeRoute =
  ShellPipelinesPipelineIdCodeRouteImport.update({
    id: '/code',
    path: '/code',
    getParentRoute: () => ShellPipelinesPipelineIdRouteRoute,
  } as any)
const ShellPipelinesPipelineIdCanvasRoute =
  ShellPipelinesPipelineIdCanvasRouteImport.update({
    id: '/canvas',
    path: '/canvas',
    getParentRoute: () => ShellPipelinesPipelineIdRouteRoute,
  } as any)
const ShellPresentationsReportsPresentationIdRouteRoute =
  ShellPresentationsReportsPresentationIdRouteRouteImport.update({
    id: '/reports/$presentationId',
    path: '/reports/$presentationId',
    getParentRoute: () => ShellPresentationsRouteRoute,
  } as any)
const ShellPresentationsDashboardsPresentationIdRouteRoute =
  ShellPresentationsDashboardsPresentationIdRouteRouteImport.update({
    id: '/dashboards/$presentationId',
    path: '/dashboards/$presentationId',
    getParentRoute: () => ShellPresentationsRouteRoute,
  } as any)
const ShellPresentationsReportsPresentationIdIndexRoute =
  ShellPresentationsReportsPresentationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellPresentationsReportsPresentationIdRouteRoute,
  } as any)
const ShellPresentationsDashboardsPresentationIdIndexRoute =
  ShellPresentationsDashboardsPresentationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellPresentationsDashboardsPresentationIdRouteRoute,
  } as any)
const ShellPresentationsReportsPresentationIdViewRoute =
  ShellPresentationsReportsPresentationIdViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => ShellPresentationsReportsPresentationIdRouteRoute,
  } as any)
const ShellPresentationsDashboardsPresentationIdViewRoute =
  ShellPresentationsDashboardsPresentationIdViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => ShellPresentationsDashboardsPresentationIdRouteRoute,
  } as any)
const ShellPipelinesPipelineIdAssetsAssetIdRouteRoute =
  ShellPipelinesPipelineIdAssetsAssetIdRouteRouteImport.update({
    id: '/assets/$assetId',
    path: '/assets/$assetId',
    getParentRoute: () => ShellPipelinesPipelineIdRouteRoute,
  } as any)
const ShellPipelinesPipelineIdAssetsAssetIdIndexRoute =
  ShellPipelinesPipelineIdAssetsAssetIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellPipelinesPipelineIdAssetsAssetIdRouteRoute,
  } as any)
const ShellPipelinesPipelineIdAssetsAssetIdSplitRoute =
  ShellPipelinesPipelineIdAssetsAssetIdSplitRouteImport.update({
    id: '/split',
    path: '/split',
    getParentRoute: () => ShellPipelinesPipelineIdAssetsAssetIdRouteRoute,
  } as any)
const ShellPipelinesPipelineIdAssetsAssetIdCodeRoute =
  ShellPipelinesPipelineIdAssetsAssetIdCodeRouteImport.update({
    id: '/code',
    path: '/code',
    getParentRoute: () => ShellPipelinesPipelineIdAssetsAssetIdRouteRoute,
  } as any)
const ShellPipelinesPipelineIdAssetsAssetIdCanvasRoute =
  ShellPipelinesPipelineIdAssetsAssetIdCanvasRouteImport.update({
    id: '/canvas',
    path: '/canvas',
    getParentRoute: () => ShellPipelinesPipelineIdAssetsAssetIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/welcome': typeof WelcomeRoute
  '/project': typeof ShellProjectRouteRouteWithChildren
  '/runs': typeof ShellRunsRouteRouteWithChildren
  '/schedules': typeof ShellSchedulesRouteRouteWithChildren
  '/catalog': typeof ShellCatalogRoute
  '/redesign/$': typeof RedesignSplatRoute
  '/redesign/': typeof RedesignIndexRoute
  '/pipelines/$pipelineId': typeof ShellPipelinesPipelineIdRouteRouteWithChildren
  '/notebooks/$notebookId': typeof ShellNotebooksNotebookIdRoute
  '/project/connections': typeof ShellProjectConnectionsRoute
  '/project/environments': typeof ShellProjectEnvironmentsRoute
  '/project/general': typeof ShellProjectGeneralRoute
  '/runs/$runId': typeof ShellRunsRunIdRoute
  '/schedules/deployments': typeof ShellSchedulesDeploymentsRoute
  '/schedules/timeline': typeof ShellSchedulesTimelineRoute
  '/notebooks/': typeof ShellNotebooksIndexRoute
  '/project/': typeof ShellProjectIndexRoute
  '/runs/': typeof ShellRunsIndexRoute
  '/schedules/': typeof ShellSchedulesIndexRoute
  '/dashboards/$presentationId': typeof ShellPresentationsDashboardsPresentationIdRouteRouteWithChildren
  '/reports/$presentationId': typeof ShellPresentationsReportsPresentationIdRouteRouteWithChildren
  '/pipelines/$pipelineId/canvas': typeof ShellPipelinesPipelineIdCanvasRoute
  '/pipelines/$pipelineId/code': typeof ShellPipelinesPipelineIdCodeRoute
  '/pipelines/$pipelineId/split': typeof ShellPipelinesPipelineIdSplitRoute
  '/dashboards/': typeof ShellPresentationsDashboardsIndexRoute
  '/reports/': typeof ShellPresentationsReportsIndexRoute
  '/pipelines/$pipelineId/': typeof ShellPipelinesPipelineIdIndexRoute
  '/pipelines/$pipelineId/assets/$assetId': typeof ShellPipelinesPipelineIdAssetsAssetIdRouteRouteWithChildren
  '/dashboards/$presentationId/view': typeof ShellPresentationsDashboardsPresentationIdViewRoute
  '/reports/$presentationId/view': typeof ShellPresentationsReportsPresentationIdViewRoute
  '/dashboards/$presentationId/': typeof ShellPresentationsDashboardsPresentationIdIndexRoute
  '/reports/$presentationId/': typeof ShellPresentationsReportsPresentationIdIndexRoute
  '/pipelines/$pipelineId/assets/$assetId/canvas': typeof ShellPipelinesPipelineIdAssetsAssetIdCanvasRoute
  '/pipelines/$pipelineId/assets/$assetId/code': typeof ShellPipelinesPipelineIdAssetsAssetIdCodeRoute
  '/pipelines/$pipelineId/assets/$assetId/split': typeof ShellPipelinesPipelineIdAssetsAssetIdSplitRoute
  '/pipelines/$pipelineId/assets/$assetId/': typeof ShellPipelinesPipelineIdAssetsAssetIdIndexRoute
}
export interface FileRoutesByTo {
  '/welcome': typeof WelcomeRoute
  '/': typeof ShellIndexRoute
  '/catalog': typeof ShellCatalogRoute
  '/redesign/$': typeof RedesignSplatRoute
  '/redesign': typeof RedesignIndexRoute
  '/notebooks/$notebookId': typeof ShellNotebooksNotebookIdRoute
  '/project/connections': typeof ShellProjectConnectionsRoute
  '/project/environments': typeof ShellProjectEnvironmentsRoute
  '/project/general': typeof ShellProjectGeneralRoute
  '/runs/$runId': typeof ShellRunsRunIdRoute
  '/schedules/deployments': typeof ShellSchedulesDeploymentsRoute
  '/schedules/timeline': typeof ShellSchedulesTimelineRoute
  '/notebooks': typeof ShellNotebooksIndexRoute
  '/project': typeof ShellProjectIndexRoute
  '/runs': typeof ShellRunsIndexRoute
  '/schedules': typeof ShellSchedulesIndexRoute
  '/pipelines/$pipelineId/canvas': typeof ShellPipelinesPipelineIdCanvasRoute
  '/pipelines/$pipelineId/code': typeof ShellPipelinesPipelineIdCodeRoute
  '/pipelines/$pipelineId/split': typeof ShellPipelinesPipelineIdSplitRoute
  '/dashboards': typeof ShellPresentationsDashboardsIndexRoute
  '/reports': typeof ShellPresentationsReportsIndexRoute
  '/pipelines/$pipelineId': typeof ShellPipelinesPipelineIdIndexRoute
  '/dashboards/$presentationId/view': typeof ShellPresentationsDashboardsPresentationIdViewRoute
  '/reports/$presentationId/view': typeof ShellPresentationsReportsPresentationIdViewRoute
  '/dashboards/$presentationId': typeof ShellPresentationsDashboardsPresentationIdIndexRoute
  '/reports/$presentationId': typeof ShellPresentationsReportsPresentationIdIndexRoute
  '/pipelines/$pipelineId/assets/$assetId/canvas': typeof ShellPipelinesPipelineIdAssetsAssetIdCanvasRoute
  '/pipelines/$pipelineId/assets/$assetId/code': typeof ShellPipelinesPipelineIdAssetsAssetIdCodeRoute
  '/pipelines/$pipelineId/assets/$assetId/split': typeof ShellPipelinesPipelineIdAssetsAssetIdSplitRoute
  '/pipelines/$pipelineId/assets/$assetId': typeof ShellPipelinesPipelineIdAssetsAssetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/_shell/_presentations': typeof ShellPresentationsRouteRouteWithChildren
  '/_shell/project': typeof ShellProjectRouteRouteWithChildren
  '/_shell/runs': typeof ShellRunsRouteRouteWithChildren
  '/_shell/schedules': typeof ShellSchedulesRouteRouteWithChildren
  '/_shell/catalog': typeof ShellCatalogRoute
  '/redesign/$': typeof RedesignSplatRoute
  '/_shell/': typeof ShellIndexRoute
  '/redesign/': typeof RedesignIndexRoute
  '/_shell/pipelines/$pipelineId': typeof ShellPipelinesPipelineIdRouteRouteWithChildren
  '/_shell/notebooks/$notebookId': typeof ShellNotebooksNotebookIdRoute
  '/_shell/project/connections': typeof ShellProjectConnectionsRoute
  '/_shell/project/environments': typeof ShellProjectEnvironmentsRoute
  '/_shell/project/general': typeof ShellProjectGeneralRoute
  '/_shell/runs/$runId': typeof ShellRunsRunIdRoute
  '/_shell/schedules/deployments': typeof ShellSchedulesDeploymentsRoute
  '/_shell/schedules/timeline': typeof ShellSchedulesTimelineRoute
  '/_shell/notebooks/': typeof ShellNotebooksIndexRoute
  '/_shell/project/': typeof ShellProjectIndexRoute
  '/_shell/runs/': typeof ShellRunsIndexRoute
  '/_shell/schedules/': typeof ShellSchedulesIndexRoute
  '/_shell/_presentations/dashboards/$presentationId': typeof ShellPresentationsDashboardsPresentationIdRouteRouteWithChildren
  '/_shell/_presentations/reports/$presentationId': typeof ShellPresentationsReportsPresentationIdRouteRouteWithChildren
  '/_shell/pipelines/$pipelineId/canvas': typeof ShellPipelinesPipelineIdCanvasRoute
  '/_shell/pipelines/$pipelineId/code': typeof ShellPipelinesPipelineIdCodeRoute
  '/_shell/pipelines/$pipelineId/split': typeof ShellPipelinesPipelineIdSplitRoute
  '/_shell/_presentations/dashboards/': typeof ShellPresentationsDashboardsIndexRoute
  '/_shell/_presentations/reports/': typeof ShellPresentationsReportsIndexRoute
  '/_shell/pipelines/$pipelineId/': typeof ShellPipelinesPipelineIdIndexRoute
  '/_shell/pipelines/$pipelineId/assets/$assetId': typeof ShellPipelinesPipelineIdAssetsAssetIdRouteRouteWithChildren
  '/_shell/_presentations/dashboards/$presentationId/view': typeof ShellPresentationsDashboardsPresentationIdViewRoute
  '/_shell/_presentations/reports/$presentationId/view': typeof ShellPresentationsReportsPresentationIdViewRoute
  '/_shell/_presentations/dashboards/$presentationId/': typeof ShellPresentationsDashboardsPresentationIdIndexRoute
  '/_shell/_presentations/reports/$presentationId/': typeof ShellPresentationsReportsPresentationIdIndexRoute
  '/_shell/pipelines/$pipelineId/assets/$assetId/canvas': typeof ShellPipelinesPipelineIdAssetsAssetIdCanvasRoute
  '/_shell/pipelines/$pipelineId/assets/$assetId/code': typeof ShellPipelinesPipelineIdAssetsAssetIdCodeRoute
  '/_shell/pipelines/$pipelineId/assets/$assetId/split': typeof ShellPipelinesPipelineIdAssetsAssetIdSplitRoute
  '/_shell/pipelines/$pipelineId/assets/$assetId/': typeof ShellPipelinesPipelineIdAssetsAssetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/project'
    | '/runs'
    | '/schedules'
    | '/catalog'
    | '/redesign/$'
    | '/redesign/'
    | '/pipelines/$pipelineId'
    | '/notebooks/$notebookId'
    | '/project/connections'
    | '/project/environments'
    | '/project/general'
    | '/runs/$runId'
    | '/schedules/deployments'
    | '/schedules/timeline'
    | '/notebooks/'
    | '/project/'
    | '/runs/'
    | '/schedules/'
    | '/dashboards/$presentationId'
    | '/reports/$presentationId'
    | '/pipelines/$pipelineId/canvas'
    | '/pipelines/$pipelineId/code'
    | '/pipelines/$pipelineId/split'
    | '/dashboards/'
    | '/reports/'
    | '/pipelines/$pipelineId/'
    | '/pipelines/$pipelineId/assets/$assetId'
    | '/dashboards/$presentationId/view'
    | '/reports/$presentationId/view'
    | '/dashboards/$presentationId/'
    | '/reports/$presentationId/'
    | '/pipelines/$pipelineId/assets/$assetId/canvas'
    | '/pipelines/$pipelineId/assets/$assetId/code'
    | '/pipelines/$pipelineId/assets/$assetId/split'
    | '/pipelines/$pipelineId/assets/$assetId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/welcome'
    | '/'
    | '/catalog'
    | '/redesign/$'
    | '/redesign'
    | '/notebooks/$notebookId'
    | '/project/connections'
    | '/project/environments'
    | '/project/general'
    | '/runs/$runId'
    | '/schedules/deployments'
    | '/schedules/timeline'
    | '/notebooks'
    | '/project'
    | '/runs'
    | '/schedules'
    | '/pipelines/$pipelineId/canvas'
    | '/pipelines/$pipelineId/code'
    | '/pipelines/$pipelineId/split'
    | '/dashboards'
    | '/reports'
    | '/pipelines/$pipelineId'
    | '/dashboards/$presentationId/view'
    | '/reports/$presentationId/view'
    | '/dashboards/$presentationId'
    | '/reports/$presentationId'
    | '/pipelines/$pipelineId/assets/$assetId/canvas'
    | '/pipelines/$pipelineId/assets/$assetId/code'
    | '/pipelines/$pipelineId/assets/$assetId/split'
    | '/pipelines/$pipelineId/assets/$assetId'
  id:
    | '__root__'
    | '/_shell'
    | '/welcome'
    | '/_shell/_presentations'
    | '/_shell/project'
    | '/_shell/runs'
    | '/_shell/schedules'
    | '/_shell/catalog'
    | '/redesign/$'
    | '/_shell/'
    | '/redesign/'
    | '/_shell/pipelines/$pipelineId'
    | '/_shell/notebooks/$notebookId'
    | '/_shell/project/connections'
    | '/_shell/project/environments'
    | '/_shell/project/general'
    | '/_shell/runs/$runId'
    | '/_shell/schedules/deployments'
    | '/_shell/schedules/timeline'
    | '/_shell/notebooks/'
    | '/_shell/project/'
    | '/_shell/runs/'
    | '/_shell/schedules/'
    | '/_shell/_presentations/dashboards/$presentationId'
    | '/_shell/_presentations/reports/$presentationId'
    | '/_shell/pipelines/$pipelineId/canvas'
    | '/_shell/pipelines/$pipelineId/code'
    | '/_shell/pipelines/$pipelineId/split'
    | '/_shell/_presentations/dashboards/'
    | '/_shell/_presentations/reports/'
    | '/_shell/pipelines/$pipelineId/'
    | '/_shell/pipelines/$pipelineId/assets/$assetId'
    | '/_shell/_presentations/dashboards/$presentationId/view'
    | '/_shell/_presentations/reports/$presentationId/view'
    | '/_shell/_presentations/dashboards/$presentationId/'
    | '/_shell/_presentations/reports/$presentationId/'
    | '/_shell/pipelines/$pipelineId/assets/$assetId/canvas'
    | '/_shell/pipelines/$pipelineId/assets/$assetId/code'
    | '/_shell/pipelines/$pipelineId/assets/$assetId/split'
    | '/_shell/pipelines/$pipelineId/assets/$assetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  RedesignSplatRoute: typeof RedesignSplatRoute
  RedesignIndexRoute: typeof RedesignIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redesign/': {
      id: '/redesign/'
      path: '/redesign'
      fullPath: '/redesign/'
      preLoaderRoute: typeof RedesignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/redesign/$': {
      id: '/redesign/$'
      path: '/redesign/$'
      fullPath: '/redesign/$'
      preLoaderRoute: typeof RedesignSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/catalog': {
      id: '/_shell/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof ShellCatalogRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/schedules': {
      id: '/_shell/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof ShellSchedulesRouteRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/runs': {
      id: '/_shell/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof ShellRunsRouteRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/project': {
      id: '/_shell/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ShellProjectRouteRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/_presentations': {
      id: '/_shell/_presentations'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellPresentationsRouteRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/schedules/': {
      id: '/_shell/schedules/'
      path: '/'
      fullPath: '/schedules/'
      preLoaderRoute: typeof ShellSchedulesIndexRouteImport
      parentRoute: typeof ShellSchedulesRouteRoute
    }
    '/_shell/runs/': {
      id: '/_shell/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof ShellRunsIndexRouteImport
      parentRoute: typeof ShellRunsRouteRoute
    }
    '/_shell/project/': {
      id: '/_shell/project/'
      path: '/'
      fullPath: '/project/'
      preLoaderRoute: typeof ShellProjectIndexRouteImport
      parentRoute: typeof ShellProjectRouteRoute
    }
    '/_shell/notebooks/': {
      id: '/_shell/notebooks/'
      path: '/notebooks'
      fullPath: '/notebooks/'
      preLoaderRoute: typeof ShellNotebooksIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/schedules/timeline': {
      id: '/_shell/schedules/timeline'
      path: '/timeline'
      fullPath: '/schedules/timeline'
      preLoaderRoute: typeof ShellSchedulesTimelineRouteImport
      parentRoute: typeof ShellSchedulesRouteRoute
    }
    '/_shell/schedules/deployments': {
      id: '/_shell/schedules/deployments'
      path: '/deployments'
      fullPath: '/schedules/deployments'
      preLoaderRoute: typeof ShellSchedulesDeploymentsRouteImport
      parentRoute: typeof ShellSchedulesRouteRoute
    }
    '/_shell/runs/$runId': {
      id: '/_shell/runs/$runId'
      path: '/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof ShellRunsRunIdRouteImport
      parentRoute: typeof ShellRunsRouteRoute
    }
    '/_shell/project/general': {
      id: '/_shell/project/general'
      path: '/general'
      fullPath: '/project/general'
      preLoaderRoute: typeof ShellProjectGeneralRouteImport
      parentRoute: typeof ShellProjectRouteRoute
    }
    '/_shell/project/environments': {
      id: '/_shell/project/environments'
      path: '/environments'
      fullPath: '/project/environments'
      preLoaderRoute: typeof ShellProjectEnvironmentsRouteImport
      parentRoute: typeof ShellProjectRouteRoute
    }
    '/_shell/project/connections': {
      id: '/_shell/project/connections'
      path: '/connections'
      fullPath: '/project/connections'
      preLoaderRoute: typeof ShellProjectConnectionsRouteImport
      parentRoute: typeof ShellProjectRouteRoute
    }
    '/_shell/notebooks/$notebookId': {
      id: '/_shell/notebooks/$notebookId'
      path: '/notebooks/$notebookId'
      fullPath: '/notebooks/$notebookId'
      preLoaderRoute: typeof ShellNotebooksNotebookIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pipelines/$pipelineId': {
      id: '/_shell/pipelines/$pipelineId'
      path: '/pipelines/$pipelineId'
      fullPath: '/pipelines/$pipelineId'
      preLoaderRoute: typeof ShellPipelinesPipelineIdRouteRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pipelines/$pipelineId/': {
      id: '/_shell/pipelines/$pipelineId/'
      path: '/'
      fullPath: '/pipelines/$pipelineId/'
      preLoaderRoute: typeof ShellPipelinesPipelineIdIndexRouteImport
      parentRoute: typeof ShellPipelinesPipelineIdRouteRoute
    }
    '/_shell/_presentations/reports/': {
      id: '/_shell/_presentations/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ShellPresentationsReportsIndexRouteImport
      parentRoute: typeof ShellPresentationsRouteRoute
    }
    '/_shell/_presentations/dashboards/': {
      id: '/_shell/_presentations/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof ShellPresentationsDashboardsIndexRouteImport
      parentRoute: typeof ShellPresentationsRouteRoute
    }
    '/_shell/pipelines/$pipelineId/split': {
      id: '/_shell/pipelines/$pipelineId/split'
      path: '/split'
      fullPath: '/pipelines/$pipelineId/split'
      preLoaderRoute: typeof ShellPipelinesPipelineIdSplitRouteImport
      parentRoute: typeof ShellPipelinesPipelineIdRouteRoute
    }
    '/_shell/pipelines/$pipelineId/code': {
      id: '/_shell/pipelines/$pipelineId/code'
      path: '/code'
      fullPath: '/pipelines/$pipelineId/code'
      preLoaderRoute: typeof ShellPipelinesPipelineIdCodeRouteImport
      parentRoute: typeof ShellPipelinesPipelineIdRouteRoute
    }
    '/_shell/pipelines/$pipelineId/canvas': {
      id: '/_shell/pipelines/$pipelineId/canvas'
      path: '/canvas'
      fullPath: '/pipelines/$pipelineId/canvas'
      preLoaderRoute: typeof ShellPipelinesPipelineIdCanvasRouteImport
      parentRoute: typeof ShellPipelinesPipelineIdRouteRoute
    }
    '/_shell/_presentations/reports/$presentationId': {
      id: '/_shell/_presentations/reports/$presentationId'
      path: '/reports/$presentationId'
      fullPath: '/reports/$presentationId'
      preLoaderRoute: typeof ShellPresentationsReportsPresentationIdRouteRouteImport
      parentRoute: typeof ShellPresentationsRouteRoute
    }
    '/_shell/_presentations/dashboards/$presentationId': {
      id: '/_shell/_presentations/dashboards/$presentationId'
      path: '/dashboards/$presentationId'
      fullPath: '/dashboards/$presentationId'
      preLoaderRoute: typeof ShellPresentationsDashboardsPresentationIdRouteRouteImport
      parentRoute: typeof ShellPresentationsRouteRoute
    }
    '/_shell/_presentations/reports/$presentationId/': {
      id: '/_shell/_presentations/reports/$presentationId/'
      path: '/'
      fullPath: '/reports/$presentationId/'
      preLoaderRoute: typeof ShellPresentationsReportsPresentationIdIndexRouteImport
      parentRoute: typeof ShellPresentationsReportsPresentationIdRouteRoute
    }
    '/_shell/_presentations/dashboards/$presentationId/': {
      id: '/_shell/_presentations/dashboards/$presentationId/'
      path: '/'
      fullPath: '/dashboards/$presentationId/'
      preLoaderRoute: typeof ShellPresentationsDashboardsPresentationIdIndexRouteImport
      parentRoute: typeof ShellPresentationsDashboardsPresentationIdRouteRoute
    }
    '/_shell/_presentations/reports/$presentationId/view': {
      id: '/_shell/_presentations/reports/$presentationId/view'
      path: '/view'
      fullPath: '/reports/$presentationId/view'
      preLoaderRoute: typeof ShellPresentationsReportsPresentationIdViewRouteImport
      parentRoute: typeof ShellPresentationsReportsPresentationIdRouteRoute
    }
    '/_shell/_presentations/dashboards/$presentationId/view': {
      id: '/_shell/_presentations/dashboards/$presentationId/view'
      path: '/view'
      fullPath: '/dashboards/$presentationId/view'
      preLoaderRoute: typeof ShellPresentationsDashboardsPresentationIdViewRouteImport
      parentRoute: typeof ShellPresentationsDashboardsPresentationIdRouteRoute
    }
    '/_shell/pipelines/$pipelineId/assets/$assetId': {
      id: '/_shell/pipelines/$pipelineId/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/pipelines/$pipelineId/assets/$assetId'
      preLoaderRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdRouteRouteImport
      parentRoute: typeof ShellPipelinesPipelineIdRouteRoute
    }
    '/_shell/pipelines/$pipelineId/assets/$assetId/': {
      id: '/_shell/pipelines/$pipelineId/assets/$assetId/'
      path: '/'
      fullPath: '/pipelines/$pipelineId/assets/$assetId/'
      preLoaderRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdIndexRouteImport
      parentRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdRouteRoute
    }
    '/_shell/pipelines/$pipelineId/assets/$assetId/split': {
      id: '/_shell/pipelines/$pipelineId/assets/$assetId/split'
      path: '/split'
      fullPath: '/pipelines/$pipelineId/assets/$assetId/split'
      preLoaderRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdSplitRouteImport
      parentRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdRouteRoute
    }
    '/_shell/pipelines/$pipelineId/assets/$assetId/code': {
      id: '/_shell/pipelines/$pipelineId/assets/$assetId/code'
      path: '/code'
      fullPath: '/pipelines/$pipelineId/assets/$assetId/code'
      preLoaderRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdCodeRouteImport
      parentRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdRouteRoute
    }
    '/_shell/pipelines/$pipelineId/assets/$assetId/canvas': {
      id: '/_shell/pipelines/$pipelineId/assets/$assetId/canvas'
      path: '/canvas'
      fullPath: '/pipelines/$pipelineId/assets/$assetId/canvas'
      preLoaderRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdCanvasRouteImport
      parentRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdRouteRoute
    }
  }
}

interface ShellPresentationsDashboardsPresentationIdRouteRouteChildren {
  ShellPresentationsDashboardsPresentationIdViewRoute: typeof ShellPresentationsDashboardsPresentationIdViewRoute
  ShellPresentationsDashboardsPresentationIdIndexRoute: typeof ShellPresentationsDashboardsPresentationIdIndexRoute
}

const ShellPresentationsDashboardsPresentationIdRouteRouteChildren: ShellPresentationsDashboardsPresentationIdRouteRouteChildren =
  {
    ShellPresentationsDashboardsPresentationIdViewRoute:
      ShellPresentationsDashboardsPresentationIdViewRoute,
    ShellPresentationsDashboardsPresentationIdIndexRoute:
      ShellPresentationsDashboardsPresentationIdIndexRoute,
  }

const ShellPresentationsDashboardsPresentationIdRouteRouteWithChildren =
  ShellPresentationsDashboardsPresentationIdRouteRoute._addFileChildren(
    ShellPresentationsDashboardsPresentationIdRouteRouteChildren,
  )

interface ShellPresentationsReportsPresentationIdRouteRouteChildren {
  ShellPresentationsReportsPresentationIdViewRoute: typeof ShellPresentationsReportsPresentationIdViewRoute
  ShellPresentationsReportsPresentationIdIndexRoute: typeof ShellPresentationsReportsPresentationIdIndexRoute
}

const ShellPresentationsReportsPresentationIdRouteRouteChildren: ShellPresentationsReportsPresentationIdRouteRouteChildren =
  {
    ShellPresentationsReportsPresentationIdViewRoute:
      ShellPresentationsReportsPresentationIdViewRoute,
    ShellPresentationsReportsPresentationIdIndexRoute:
      ShellPresentationsReportsPresentationIdIndexRoute,
  }

const ShellPresentationsReportsPresentationIdRouteRouteWithChildren =
  ShellPresentationsReportsPresentationIdRouteRoute._addFileChildren(
    ShellPresentationsReportsPresentationIdRouteRouteChildren,
  )

interface ShellPresentationsRouteRouteChildren {
  ShellPresentationsDashboardsPresentationIdRouteRoute: typeof ShellPresentationsDashboardsPresentationIdRouteRouteWithChildren
  ShellPresentationsReportsPresentationIdRouteRoute: typeof ShellPresentationsReportsPresentationIdRouteRouteWithChildren
  ShellPresentationsDashboardsIndexRoute: typeof ShellPresentationsDashboardsIndexRoute
  ShellPresentationsReportsIndexRoute: typeof ShellPresentationsReportsIndexRoute
}

const ShellPresentationsRouteRouteChildren: ShellPresentationsRouteRouteChildren =
  {
    ShellPresentationsDashboardsPresentationIdRouteRoute:
      ShellPresentationsDashboardsPresentationIdRouteRouteWithChildren,
    ShellPresentationsReportsPresentationIdRouteRoute:
      ShellPresentationsReportsPresentationIdRouteRouteWithChildren,
    ShellPresentationsDashboardsIndexRoute:
      ShellPresentationsDashboardsIndexRoute,
    ShellPresentationsReportsIndexRoute: ShellPresentationsReportsIndexRoute,
  }

const ShellPresentationsRouteRouteWithChildren =
  ShellPresentationsRouteRoute._addFileChildren(
    ShellPresentationsRouteRouteChildren,
  )

interface ShellProjectRouteRouteChildren {
  ShellProjectConnectionsRoute: typeof ShellProjectConnectionsRoute
  ShellProjectEnvironmentsRoute: typeof ShellProjectEnvironmentsRoute
  ShellProjectGeneralRoute: typeof ShellProjectGeneralRoute
  ShellProjectIndexRoute: typeof ShellProjectIndexRoute
}

const ShellProjectRouteRouteChildren: ShellProjectRouteRouteChildren = {
  ShellProjectConnectionsRoute: ShellProjectConnectionsRoute,
  ShellProjectEnvironmentsRoute: ShellProjectEnvironmentsRoute,
  ShellProjectGeneralRoute: ShellProjectGeneralRoute,
  ShellProjectIndexRoute: ShellProjectIndexRoute,
}

const ShellProjectRouteRouteWithChildren =
  ShellProjectRouteRoute._addFileChildren(ShellProjectRouteRouteChildren)

interface ShellRunsRouteRouteChildren {
  ShellRunsRunIdRoute: typeof ShellRunsRunIdRoute
  ShellRunsIndexRoute: typeof ShellRunsIndexRoute
}

const ShellRunsRouteRouteChildren: ShellRunsRouteRouteChildren = {
  ShellRunsRunIdRoute: ShellRunsRunIdRoute,
  ShellRunsIndexRoute: ShellRunsIndexRoute,
}

const ShellRunsRouteRouteWithChildren = ShellRunsRouteRoute._addFileChildren(
  ShellRunsRouteRouteChildren,
)

interface ShellSchedulesRouteRouteChildren {
  ShellSchedulesDeploymentsRoute: typeof ShellSchedulesDeploymentsRoute
  ShellSchedulesTimelineRoute: typeof ShellSchedulesTimelineRoute
  ShellSchedulesIndexRoute: typeof ShellSchedulesIndexRoute
}

const ShellSchedulesRouteRouteChildren: ShellSchedulesRouteRouteChildren = {
  ShellSchedulesDeploymentsRoute: ShellSchedulesDeploymentsRoute,
  ShellSchedulesTimelineRoute: ShellSchedulesTimelineRoute,
  ShellSchedulesIndexRoute: ShellSchedulesIndexRoute,
}

const ShellSchedulesRouteRouteWithChildren =
  ShellSchedulesRouteRoute._addFileChildren(ShellSchedulesRouteRouteChildren)

interface ShellPipelinesPipelineIdAssetsAssetIdRouteRouteChildren {
  ShellPipelinesPipelineIdAssetsAssetIdCanvasRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdCanvasRoute
  ShellPipelinesPipelineIdAssetsAssetIdCodeRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdCodeRoute
  ShellPipelinesPipelineIdAssetsAssetIdSplitRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdSplitRoute
  ShellPipelinesPipelineIdAssetsAssetIdIndexRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdIndexRoute
}

const ShellPipelinesPipelineIdAssetsAssetIdRouteRouteChildren: ShellPipelinesPipelineIdAssetsAssetIdRouteRouteChildren =
  {
    ShellPipelinesPipelineIdAssetsAssetIdCanvasRoute:
      ShellPipelinesPipelineIdAssetsAssetIdCanvasRoute,
    ShellPipelinesPipelineIdAssetsAssetIdCodeRoute:
      ShellPipelinesPipelineIdAssetsAssetIdCodeRoute,
    ShellPipelinesPipelineIdAssetsAssetIdSplitRoute:
      ShellPipelinesPipelineIdAssetsAssetIdSplitRoute,
    ShellPipelinesPipelineIdAssetsAssetIdIndexRoute:
      ShellPipelinesPipelineIdAssetsAssetIdIndexRoute,
  }

const ShellPipelinesPipelineIdAssetsAssetIdRouteRouteWithChildren =
  ShellPipelinesPipelineIdAssetsAssetIdRouteRoute._addFileChildren(
    ShellPipelinesPipelineIdAssetsAssetIdRouteRouteChildren,
  )

interface ShellPipelinesPipelineIdRouteRouteChildren {
  ShellPipelinesPipelineIdCanvasRoute: typeof ShellPipelinesPipelineIdCanvasRoute
  ShellPipelinesPipelineIdCodeRoute: typeof ShellPipelinesPipelineIdCodeRoute
  ShellPipelinesPipelineIdSplitRoute: typeof ShellPipelinesPipelineIdSplitRoute
  ShellPipelinesPipelineIdIndexRoute: typeof ShellPipelinesPipelineIdIndexRoute
  ShellPipelinesPipelineIdAssetsAssetIdRouteRoute: typeof ShellPipelinesPipelineIdAssetsAssetIdRouteRouteWithChildren
}

const ShellPipelinesPipelineIdRouteRouteChildren: ShellPipelinesPipelineIdRouteRouteChildren =
  {
    ShellPipelinesPipelineIdCanvasRoute: ShellPipelinesPipelineIdCanvasRoute,
    ShellPipelinesPipelineIdCodeRoute: ShellPipelinesPipelineIdCodeRoute,
    ShellPipelinesPipelineIdSplitRoute: ShellPipelinesPipelineIdSplitRoute,
    ShellPipelinesPipelineIdIndexRoute: ShellPipelinesPipelineIdIndexRoute,
    ShellPipelinesPipelineIdAssetsAssetIdRouteRoute:
      ShellPipelinesPipelineIdAssetsAssetIdRouteRouteWithChildren,
  }

const ShellPipelinesPipelineIdRouteRouteWithChildren =
  ShellPipelinesPipelineIdRouteRoute._addFileChildren(
    ShellPipelinesPipelineIdRouteRouteChildren,
  )

interface ShellRouteChildren {
  ShellPresentationsRouteRoute: typeof ShellPresentationsRouteRouteWithChildren
  ShellProjectRouteRoute: typeof ShellProjectRouteRouteWithChildren
  ShellRunsRouteRoute: typeof ShellRunsRouteRouteWithChildren
  ShellSchedulesRouteRoute: typeof ShellSchedulesRouteRouteWithChildren
  ShellCatalogRoute: typeof ShellCatalogRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellPipelinesPipelineIdRouteRoute: typeof ShellPipelinesPipelineIdRouteRouteWithChildren
  ShellNotebooksNotebookIdRoute: typeof ShellNotebooksNotebookIdRoute
  ShellNotebooksIndexRoute: typeof ShellNotebooksIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellPresentationsRouteRoute: ShellPresentationsRouteRouteWithChildren,
  ShellProjectRouteRoute: ShellProjectRouteRouteWithChildren,
  ShellRunsRouteRoute: ShellRunsRouteRouteWithChildren,
  ShellSchedulesRouteRoute: ShellSchedulesRouteRouteWithChildren,
  ShellCatalogRoute: ShellCatalogRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellPipelinesPipelineIdRouteRoute:
    ShellPipelinesPipelineIdRouteRouteWithChildren,
  ShellNotebooksNotebookIdRoute: ShellNotebooksNotebookIdRoute,
  ShellNotebooksIndexRoute: ShellNotebooksIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  RedesignSplatRoute: RedesignSplatRoute,
  RedesignIndexRoute: RedesignIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
