package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const generatedHeader = "// Code generated by internal/tools/apitypes. DO NOT EDIT.\n\n"

var typescriptIdentifier = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

type contractTypeKey struct {
	packagePath string
	name        string
}

func (k contractTypeKey) String() string {
	return k.packagePath + "." + k.name
}

type contractTypeDecl struct {
	key          contractTypeKey
	spec         *ast.TypeSpec
	imports      map[string]string
	root         bool
	typeScriptID string
}

type contractEnumValue struct {
	position token.Pos
	value    string
}

type renderedContractType struct {
	key  contractTypeKey
	name string
	body string
}

type apiTypeGenerator struct {
	types        map[contractTypeKey]*contractTypeDecl
	enums        map[contractTypeKey][]contractEnumValue
	roots        []contractTypeKey
	states       map[contractTypeKey]uint8
	typeNames    map[contractTypeKey]string
	byName       map[string]renderedContractType
	declarations []renderedContractType
}

func generateAPITypeScript(repoRoot string) (string, error) {
	generator := &apiTypeGenerator{
		types:     make(map[contractTypeKey]*contractTypeDecl),
		enums:     make(map[contractTypeKey][]contractEnumValue),
		states:    make(map[contractTypeKey]uint8),
		typeNames: make(map[contractTypeKey]string),
		byName:    make(map[string]renderedContractType),
	}
	if err := generator.scan(filepath.Join(repoRoot, "internal", "web"), repoRoot); err != nil {
		return "", err
	}
	if len(generator.roots) == 0 {
		return "", fmt.Errorf("no // renart:web contract roots found under internal/web")
	}
	sort.Slice(generator.roots, func(i, j int) bool {
		return generator.roots[i].String() < generator.roots[j].String()
	})
	for _, root := range generator.roots {
		if _, err := generator.ensureNamed(root); err != nil {
			return "", err
		}
	}
	sort.Slice(generator.declarations, func(i, j int) bool {
		return generator.declarations[i].name < generator.declarations[j].name
	})
	blocks := make([]string, 0, len(generator.declarations))
	for _, declaration := range generator.declarations {
		blocks = append(blocks, "export type "+declaration.name+" = "+declaration.body+";")
	}
	return generatedHeader + strings.Join(blocks, "\n\n") + "\n", nil
}

func (g *apiTypeGenerator) scan(scanRoot, repoRoot string) error {
	modulePath, err := readModulePath(filepath.Join(repoRoot, "go.mod"))
	if err != nil {
		return err
	}
	fset := token.NewFileSet()
	err = filepath.WalkDir(scanRoot, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			if entry.Name() == "testdata" || strings.HasPrefix(entry.Name(), ".") {
				if path != scanRoot {
					return filepath.SkipDir
				}
			}
			return nil
		}
		if !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			return nil
		}
		parsed, parseErr := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if parseErr != nil {
			return fmt.Errorf("parse %s: %w", path, parseErr)
		}
		relativeDir, relErr := filepath.Rel(repoRoot, filepath.Dir(path))
		if relErr != nil {
			return relErr
		}
		packagePath := modulePath + "/" + filepath.ToSlash(relativeDir)
		imports := fileImports(parsed)
		for _, declaration := range parsed.Decls {
			gen, ok := declaration.(*ast.GenDecl)
			if !ok {
				continue
			}
			switch gen.Tok {
			case token.TYPE:
				for _, rawSpec := range gen.Specs {
					spec := rawSpec.(*ast.TypeSpec)
					key := contractTypeKey{packagePath: packagePath, name: spec.Name.Name}
					if existing := g.types[key]; existing != nil {
						return fmt.Errorf("duplicate contract type %s", key)
					}
					directives := append(commentLines(gen.Doc), commentLines(spec.Doc)...)
					decl := &contractTypeDecl{
						key:          key,
						spec:         spec,
						imports:      imports,
						root:         hasDirective(directives, "renart:web"),
						typeScriptID: directiveValue(directives, "renart:web-name"),
					}
					g.types[key] = decl
					if decl.root {
						g.roots = append(g.roots, key)
					}
				}
			case token.CONST:
				g.scanConstants(packagePath, gen)
			}
		}
		return nil
	})
	if err != nil {
		return fmt.Errorf("scan Go API contracts: %w", err)
	}
	return nil
}

func readModulePath(path string) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read go.mod: %w", err)
	}
	for _, line := range strings.Split(string(content), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 2 && fields[0] == "module" {
			return fields[1], nil
		}
	}
	return "", fmt.Errorf("module directive not found in %s", path)
}

func fileImports(file *ast.File) map[string]string {
	result := make(map[string]string, len(file.Imports))
	for _, item := range file.Imports {
		path, err := strconv.Unquote(item.Path.Value)
		if err != nil {
			continue
		}
		name := filepath.Base(path)
		if item.Name != nil {
			name = item.Name.Name
		}
		if name == "_" || name == "." {
			continue
		}
		result[name] = path
	}
	return result
}

func commentLines(group *ast.CommentGroup) []string {
	if group == nil {
		return nil
	}
	result := make([]string, 0, len(group.List))
	for _, comment := range group.List {
		text := strings.TrimSpace(comment.Text)
		text = strings.TrimSpace(strings.TrimPrefix(text, "//"))
		text = strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(text, "/*"), "*/"))
		result = append(result, strings.Split(text, "\n")...)
	}
	return result
}

func hasDirective(lines []string, directive string) bool {
	for _, line := range lines {
		if strings.TrimSpace(line) == directive {
			return true
		}
	}
	return false
}

func directiveValue(lines []string, directive string) string {
	prefix := directive + " "
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, prefix) {
			return strings.TrimSpace(strings.TrimPrefix(line, prefix))
		}
	}
	return ""
}

func (g *apiTypeGenerator) scanConstants(packagePath string, declaration *ast.GenDecl) {
	for _, rawSpec := range declaration.Specs {
		spec := rawSpec.(*ast.ValueSpec)
		identifier, ok := spec.Type.(*ast.Ident)
		if !ok {
			continue
		}
		key := contractTypeKey{packagePath: packagePath, name: identifier.Name}
		for index, rawValue := range spec.Values {
			literal, ok := rawValue.(*ast.BasicLit)
			if !ok || literal.Kind != token.STRING || index >= len(spec.Names) {
				continue
			}
			value, err := strconv.Unquote(literal.Value)
			if err != nil {
				continue
			}
			g.enums[key] = append(g.enums[key], contractEnumValue{position: spec.Names[index].Pos(), value: value})
		}
	}
}

func (g *apiTypeGenerator) ensureNamed(key contractTypeKey) (string, error) {
	if name := g.typeNames[key]; name != "" {
		return name, nil
	}
	decl := g.types[key]
	if decl == nil {
		return "", fmt.Errorf("referenced contract type %s was not found under internal/web", key)
	}
	if decl.spec.Assign.IsValid() {
		return g.typeScriptType(decl.spec.Type, decl)
	}
	name := decl.typeScriptID
	if name == "" {
		name = key.name
	}
	if !typescriptIdentifier.MatchString(name) {
		return "", fmt.Errorf("invalid TypeScript name %q for %s", name, key)
	}
	g.typeNames[key] = name
	if g.states[key] == 1 {
		return name, nil
	}
	if g.states[key] == 2 {
		return name, nil
	}
	g.states[key] = 1

	body, err := g.renderNamedBody(decl)
	if err != nil {
		return "", fmt.Errorf("render %s: %w", key, err)
	}
	rendered := renderedContractType{key: key, name: name, body: body}
	if existing, exists := g.byName[name]; exists {
		if existing.body != body {
			return "", fmt.Errorf("TypeScript name %s has incompatible Go definitions %s and %s", name, existing.key, key)
		}
		g.states[key] = 2
		return name, nil
	}
	g.byName[name] = rendered
	g.declarations = append(g.declarations, rendered)
	g.states[key] = 2
	return name, nil
}

func (g *apiTypeGenerator) renderNamedBody(decl *contractTypeDecl) (string, error) {
	if structure, ok := decl.spec.Type.(*ast.StructType); ok {
		properties, err := g.structProperties(structure, decl, make(map[contractTypeKey]bool))
		if err != nil {
			return "", err
		}
		return renderObject(properties), nil
	}
	values := append([]contractEnumValue(nil), g.enums[decl.key]...)
	if len(values) > 0 {
		sort.Slice(values, func(i, j int) bool { return values[i].position < values[j].position })
		members := make([]string, 0, len(values))
		seen := make(map[string]bool, len(values))
		for _, value := range values {
			if seen[value.value] {
				continue
			}
			seen[value.value] = true
			members = append(members, strconv.Quote(value.value))
		}
		return strings.Join(members, " | "), nil
	}
	return g.typeScriptType(decl.spec.Type, decl)
}

type contractProperty struct {
	name     string
	optional bool
	typeName string
}

func (g *apiTypeGenerator) structProperties(structure *ast.StructType, decl *contractTypeDecl, embedding map[contractTypeKey]bool) ([]contractProperty, error) {
	properties := make([]contractProperty, 0, len(structure.Fields.List))
	for _, field := range structure.Fields.List {
		tagName, optional, ignored, hasName := jsonField(field)
		if ignored {
			continue
		}
		if len(field.Names) == 0 && !hasName {
			embedded, err := g.embeddedProperties(field.Type, decl, embedding)
			if err != nil {
				return nil, err
			}
			properties = append(properties, embedded...)
			continue
		}
		typeName, err := g.typeScriptType(field.Type, decl)
		if err != nil {
			return nil, err
		}
		for _, name := range field.Names {
			propertyName := tagName
			if !hasName {
				propertyName = name.Name
			}
			properties = append(properties, contractProperty{name: propertyName, optional: optional, typeName: typeName})
		}
	}
	return properties, nil
}

func jsonField(field *ast.Field) (name string, optional, ignored, hasName bool) {
	if field.Tag == nil {
		return "", false, false, false
	}
	raw, err := strconv.Unquote(field.Tag.Value)
	if err != nil {
		return "", false, false, false
	}
	value := reflect.StructTag(raw).Get("json")
	if value == "" {
		return "", false, false, false
	}
	parts := strings.Split(value, ",")
	if parts[0] == "-" {
		return "", false, true, true
	}
	for _, option := range parts[1:] {
		if option == "omitempty" {
			optional = true
		}
	}
	return parts[0], optional, false, parts[0] != ""
}

func (g *apiTypeGenerator) embeddedProperties(expression ast.Expr, context *contractTypeDecl, embedding map[contractTypeKey]bool) ([]contractProperty, error) {
	for {
		pointer, ok := expression.(*ast.StarExpr)
		if !ok {
			break
		}
		expression = pointer.X
	}
	key, ok := g.expressionTypeKey(expression, context)
	if !ok {
		return nil, fmt.Errorf("unsupported embedded field %T", expression)
	}
	if embedding[key] {
		return nil, fmt.Errorf("recursive embedded contract type %s", key)
	}
	decl := g.types[key]
	if decl == nil {
		return nil, fmt.Errorf("embedded contract type %s was not found", key)
	}
	if decl.spec.Assign.IsValid() {
		return g.embeddedProperties(decl.spec.Type, decl, embedding)
	}
	structure, ok := decl.spec.Type.(*ast.StructType)
	if !ok {
		return nil, fmt.Errorf("embedded contract type %s is not a struct", key)
	}
	embedding[key] = true
	properties, err := g.structProperties(structure, decl, embedding)
	delete(embedding, key)
	return properties, err
}

func (g *apiTypeGenerator) typeScriptType(expression ast.Expr, context *contractTypeDecl) (string, error) {
	switch value := expression.(type) {
	case *ast.Ident:
		switch value.Name {
		case "string":
			return "string", nil
		case "bool":
			return "boolean", nil
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "float32", "float64", "byte", "rune":
			return "number", nil
		case "any":
			return "unknown", nil
		}
		return g.ensureNamed(contractTypeKey{packagePath: context.key.packagePath, name: value.Name})
	case *ast.StarExpr:
		return g.typeScriptType(value.X, context)
	case *ast.ArrayType:
		element, err := g.typeScriptType(value.Elt, context)
		if err != nil {
			return "", err
		}
		if strings.Contains(element, " | ") || strings.HasPrefix(element, "{") {
			return "Array<" + element + ">", nil
		}
		return element + "[]", nil
	case *ast.MapType:
		key, err := g.typeScriptType(value.Key, context)
		if err != nil {
			return "", err
		}
		if key != "string" {
			return "", fmt.Errorf("map key must serialize as string, got %s", key)
		}
		element, err := g.typeScriptType(value.Value, context)
		if err != nil {
			return "", err
		}
		return "Record<string, " + element + ">", nil
	case *ast.SelectorExpr:
		qualifier, ok := value.X.(*ast.Ident)
		if !ok {
			return "", fmt.Errorf("unsupported selected type %T", value.X)
		}
		packagePath := context.imports[qualifier.Name]
		qualified := packagePath + "." + value.Sel.Name
		switch qualified {
		case "time.Time":
			return "string", nil
		case "time.Duration":
			return "number", nil
		case "encoding/json.RawMessage":
			return "unknown", nil
		}
		return g.ensureNamed(contractTypeKey{packagePath: packagePath, name: value.Sel.Name})
	case *ast.InterfaceType:
		if value.Methods == nil || len(value.Methods.List) == 0 {
			return "unknown", nil
		}
		return "", fmt.Errorf("non-empty interface fields are not supported")
	case *ast.StructType:
		properties, err := g.structProperties(value, context, make(map[contractTypeKey]bool))
		if err != nil {
			return "", err
		}
		return renderObject(properties), nil
	case *ast.ParenExpr:
		return g.typeScriptType(value.X, context)
	case *ast.Ellipsis:
		element, err := g.typeScriptType(value.Elt, context)
		if err != nil {
			return "", err
		}
		return element + "[]", nil
	default:
		return "", fmt.Errorf("unsupported Go type expression %T", expression)
	}
}

func (g *apiTypeGenerator) expressionTypeKey(expression ast.Expr, context *contractTypeDecl) (contractTypeKey, bool) {
	switch value := expression.(type) {
	case *ast.Ident:
		return contractTypeKey{packagePath: context.key.packagePath, name: value.Name}, true
	case *ast.SelectorExpr:
		qualifier, ok := value.X.(*ast.Ident)
		if !ok {
			return contractTypeKey{}, false
		}
		return contractTypeKey{packagePath: context.imports[qualifier.Name], name: value.Sel.Name}, true
	case *ast.StarExpr:
		return g.expressionTypeKey(value.X, context)
	default:
		return contractTypeKey{}, false
	}
}

func renderObject(properties []contractProperty) string {
	lines := make([]string, 0, len(properties))
	seen := make(map[string]bool, len(properties))
	for _, property := range properties {
		if seen[property.name] {
			continue
		}
		seen[property.name] = true
		name := property.name
		if !typescriptIdentifier.MatchString(name) {
			name = strconv.Quote(name)
		}
		optional := ""
		if property.optional {
			optional = "?"
		}
		lines = append(lines, "  "+name+optional+": "+property.typeName+";")
	}
	if len(lines) == 0 {
		return "{}"
	}
	return "{\n" + strings.Join(lines, "\n") + "\n}"
}
